benchmarks/build.gradle.kts
gradle.properties
wrapper/build.gradle.kts
wrapper/src/test/build.gradle.kts

chore: remove dynamic versioning

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/workflows/run-integration-tests.yml
README.md

Add extra badges to the readme.
- add a Maven badge
- add a Javadoc badge
@sergiyvamz 
@hsuamz

chore: Add Maven badges and update workflows

---

README.md

Fixes image badge issues for Maven and JavaDoc badges.
- Correct Maven badge SVG.
- Correct JavaDoc badge SVG.

docs: fix for Maven and JavaDoc badges not showing correctly

---

wrapper/src/main/java/software/amazon/jdbc/PluginServiceImpl.java
wrapper/src/main/java/software/amazon/jdbc/plugin/failover/FailoverConnectionPlugin.java
wrapper/src/test/java/integration/container/aurora/TestPluginServiceImpl.java
wrapper/src/test/java/integration/container/aurora/mysql/AuroraMysqlBaseTest.java
wrapper/src/test/java/integration/container/aurora/mysql/mariadbdriver/AuroraMysqlIntegrationTest.java
wrapper/src/test/java/integration/container/aurora/mysql/mysqldriver/AuroraMysqlIntegrationTest.java
wrapper/src/test/java/integration/container/aurora/postgres/AuroraPostgresBaseTest.java
wrapper/src/test/java/integration/container/aurora/postgres/AuroraPostgresIntegrationTest.java
wrapper/src/test/java/software/amazon/jdbc/PluginServiceImplTests.java

Cache host availability so new topology information contains the correct host availability
@sergiyvamz 
@joyc-bq 
@alecc-bq 
@congoamz

refactor: cache host status

---

docs/using-the-jdbc-driver/using-plugins/UsingTheFailoverPlugin.md
wrapper/src/main/java/software/amazon/jdbc/util/HikariCPSQLException.java
wrapper/src/test/java/integration/container/aurora/mysql/AuroraMysqlBaseTest.java
wrapper/src/test/java/integration/container/aurora/mysql/mariadbdriver/AuroraMysqlFailoverTest.java
wrapper/src/test/java/integration/container/aurora/mysql/mariadbdriver/AuroraMysqlIntegrationTest.java
wrapper/src/test/java/integration/container/aurora/mysql/mariadbdriver/HikariCPIntegrationTest.java
wrapper/src/test/java/integration/container/aurora/mysql/mariadbdriver/MariadbAuroraMysqlTestSuite.java
wrapper/src/test/java/integration/container/aurora/mysql/mysqldriver/AuroraMysqlFailoverTest.java
wrapper/src/test/java/integration/container/aurora/mysql/mysqldriver/AuroraMysqlIntegrationTest.java
wrapper/src/test/java/integration/container/aurora/mysql/mysqldriver/MysqlAuroraMysqlTestSuite.java
wrapper/src/test/java/integration/container/aurora/postgres/AuroraPostgresBaseTest.java
wrapper/src/test/java/integration/container/aurora/postgres/AuroraPostgresFailoverTest.java
wrapper/src/test/java/integration/container/aurora/postgres/AuroraPostgresIntegrationTest.java
wrapper/src/test/java/integration/container/aurora/postgres/AuroraPostgresTestSuite.java
wrapper/src/test/java/integration/container/aurora/postgres/HikariCPIntegrationTest.java

Reviewers
@sergiyvamz 
@karenc-bq

Add Hikari integration tests

---

.github/workflows/mysql_performance.yml
.github/workflows/pg_performance.yml

chore: fix performance test workflow for mysql
@sergiyvamz

chore: fix performance test workflow for mysql

---

wrapper/src/main/java/software/amazon/jdbc/hostlistprovider/AuroraHostListProvider.java

Added missing spaces to sql commands

Fixed missing spaces in sql for mysql topology query

---

wrapper/build.gradle.kts
wrapper/src/main/java/software/amazon/jdbc/util/ConnectionUrlBuilder.java
wrapper/src/test/build.gradle.kts
wrapper/src/test/java/software/amazon/jdbc/plugin/DataCacheConnectionPluginTest.java
wrapper/src/test/java/software/amazon/jdbc/plugin/LogQueryConnectionPluginTest.java
wrapper/src/test/java/software/amazon/jdbc/plugin/efm/HostMonitoringConnectionPluginTest.java
wrapper/src/test/java/software/amazon/jdbc/plugin/efm/MonitorConnectionContextTest.java
wrapper/src/test/java/software/amazon/jdbc/plugin/efm/MonitorServiceImplTest.java
wrapper/src/test/java/software/amazon/jdbc/util/ConnectionUrlBuilderTest.java

Adding unit tests and configuring Jacoco

test: adding unit tests

---

docs/GettingStarted.md

Update postgres JDBC version to 42.5.0

Update pgjdbc version

---

wrapper/src/test/java/software/amazon/jdbc/plugin/failover/ClusterAwareReaderFailoverHandlerTest.java

Adds a unit test for the recent work done here: https://github.com/awslabs/aws-advanced-jdbc-wrapper/commit/5bc5492a57f0ea56519708163776bae76bcece8e

Unit test for strict reader failover functionality

---

wrapper/src/main/java/software/amazon/jdbc/hostlistprovider/AuroraHostListProvider.java
wrapper/src/main/resources/messages.properties
wrapper/src/test/java/software/amazon/jdbc/hostlistprovider/AuroraHostListProviderTest.java

RDS-1192
- Throw an exception with a message when topology statement throws an exception

Make AuroraHostListProvider raise exception on topology SQL syntax errors

---

examples/HikariExample/src/main/java/software/amazon/HikariFailoverExample.java

Add a failover-specific example.

doc: update Hikari failover examples

---

.editorconfig

new PR against main instead of #260

Copied editorconfig from pgjdbc

---

wrapper/build.gradle.kts
wrapper/src/main/java/software/amazon/jdbc/PluginService.java
wrapper/src/main/java/software/amazon/jdbc/PluginServiceImpl.java
wrapper/src/main/java/software/amazon/jdbc/exceptions/ExceptionHandler.java
wrapper/src/main/java/software/amazon/jdbc/exceptions/ExceptionManager.java
wrapper/src/main/java/software/amazon/jdbc/exceptions/GenericExceptionHandler.java
wrapper/src/main/java/software/amazon/jdbc/exceptions/MariaDBExceptionHandler.java
wrapper/src/main/java/software/amazon/jdbc/exceptions/MySQLExceptionHandler.java
wrapper/src/main/java/software/amazon/jdbc/exceptions/PgExceptionHandler.java
wrapper/src/main/java/software/amazon/jdbc/plugin/AwsSecretsManagerConnectionPlugin.java
wrapper/src/main/java/software/amazon/jdbc/plugin/failover/ClusterAwareReaderFailoverHandler.java
wrapper/src/main/java/software/amazon/jdbc/plugin/failover/ClusterAwareWriterFailoverHandler.java
wrapper/src/main/java/software/amazon/jdbc/plugin/failover/FailoverConnectionPlugin.java
wrapper/src/main/java/software/amazon/jdbc/util/SqlState.java
wrapper/src/test/java/integration/container/aurora/postgres/AuroraPostgresDataSourceTest.java
wrapper/src/test/java/software/amazon/jdbc/plugin/AwsSecretsManagerConnectionPluginTest.java
wrapper/src/test/java/software/amazon/jdbc/plugin/efm/ConcurrencyTests.java
wrapper/src/test/java/software/amazon/jdbc/plugin/failover/ClusterAwareReaderFailoverHandlerTest.java
wrapper/src/test/java/software/amazon/jdbc/plugin/failover/ClusterAwareWriterFailoverHandlerTest.java

Implement exception manager to handle driver-specific nested exceptions

---

wrapper/src/main/java/software/amazon/jdbc/PluginServiceImpl.java

Fix typo in `PluginServiceImpl` where `isNetworkException` calls `isLoginException`
@sergiyvamz 
@congoamz

fix: typo in PluginServiceImpl

---

wrapper/build.gradle.kts

Avoid build fail when there's no html summary report
@aaron-congo 
@karenc-bq

avoid build fail when there's no html summary report

---

examples/HibernateExample/build.gradle
examples/HikariExample/build.gradle.kts

The Hikari example project was using a specific released version of the driver instead of the latest changes in the project.

chore: update the project dependency in example subprojects

---

.github/pull_request_template.md

Adding to the PR Template

---

benchmarks/build.gradle.kts
wrapper/build.gradle.kts
wrapper/src/test/build.gradle.kts
wrapper/src/test/java/integration/refactored/container/tests/AuroraReadWriteSplittingPerformanceTest.java

RDS-1265: Wrapper - Migrate AuroraPostgresReadWriteSplittingPerformanceTest to refactored integration test suite
@karenc-bq 
@aaron-congo 
@joyc-bq

add RW split performance tests

---

.github/workflows/main.yml
.github/workflows/maven_release.yml
.github/workflows/maven_snapshot.yml
.github/workflows/mysql_performance.yml
.github/workflows/pg_performance.yml
.github/workflows/release_draft.yml
.github/workflows/run-integration-tests.yml
.github/workflows/run-standard-integration-tests.yml

Update Action versioning
#310 
@brunos-bq
@joyc-bq 

chore: update action versioning

---

.editorconfig

Change editorconfig to match checkstyle import order

Change editorconfig to match checkstyle import order

---

docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
gradle.properties

chore: update driver version to 1.0.1
@joyc-bq 

chore: update driver version to 1.0.1

---

examples/AWSDriverExample/build.gradle.kts
examples/AWSDriverExample/src/main/java/software/amazon/ReadWriteSplittingSpringJdbcTemplateExample.java

add rw plugin  example using spring jdbc template
add rw plugin  example using spring jdbc template
@karenc-bq @aaron-congo @sergiyv-improving

add rw test example with spring jdbc template

---

wrapper/src/main/java/software/amazon/jdbc/plugin/AwsSecretsManagerConnectionPlugin.java
wrapper/src/main/java/software/amazon/jdbc/plugin/IamAuthConnectionPlugin.java
wrapper/src/main/resources/messages.properties
wrapper/src/test/java/software/amazon/jdbc/plugin/IamAuthConnectionPluginTest.java

Test that link is working in this error message: 
IamAuthConnectionPlugin.unsupportedRegion=Unsupported AWS region ''{0}''. For supported regions, please read https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html

Test if AWS supported region url exists

---

benchmarks/build.gradle.kts
wrapper/build.gradle.kts
wrapper/src/test/build.gradle.kts
wrapper/src/test/java/integration/refactored/container/tests/AuroraFailoverTest.java
wrapper/src/test/java/integration/refactored/host/TestEnvironment.java
wrapper/src/test/java/integration/refactored/host/TestEnvironmentProvider.java
wrapper/src/test/java/integration/util/AuroraTestUtility.java
wrapper/src/test/resources/logging-test.properties

add 2 node (1 writer + 1 reader) test cluster configuration
@karenc-bq 
@congoamz

Add 2-node test cluster configuration

---

examples/AWSDriverExample/build.gradle.kts
examples/HikariExample/build.gradle.kts

Add missing MySQL driver dependency.

chore: add missing MySQL driver dependency to the examples

---

docs/Documentation.md
docs/KnownLimitations.md

…port blue/green deployments
@sergiyv-improving @karenc-bq @aaron-congo

doc: update documentation to reflect that wrapper driver does not support blue/green deployments

---

README.md

docs: add messaging about monthly release cadence

---

wrapper/src/test/java/integration/refactored/container/ConnectionStringHelper.java
wrapper/src/test/java/integration/refactored/container/ProxyHelper.java
wrapper/src/test/java/integration/util/AuroraTestUtility.java
wrapper/src/test/java/integration/util/ConsoleConsumer.java
wrapper/src/test/java/integration/util/ContainerHelper.java

Remove unused helper methods left over after deleting the old integration test suite

chore: delete unused methods

---

wrapper/src/test/java/integration/refactored/container/tests/AuroraFailoverTest.java

test: add delay to flakey test

---

examples/AWSDriverExample/build.gradle.kts
wrapper/build.gradle.kts
wrapper/src/main/java/software/amazon/jdbc/DataSourceConnectionProvider.java
wrapper/src/main/java/software/amazon/jdbc/dialect/AuroraPgDialect.java
wrapper/src/main/java/software/amazon/jdbc/dialect/DialectManager.java
wrapper/src/main/java/software/amazon/jdbc/plugin/AuroraConnectionTrackerPlugin.java
wrapper/src/main/java/software/amazon/jdbc/util/PropertyUtils.java
wrapper/src/test/build.gradle.kts
wrapper/src/test/java/integration/refactored/container/tests/AuroraFailoverTest.java
wrapper/src/test/java/integration/refactored/container/tests/HikariTests.java
wrapper/src/test/java/integration/refactored/container/tests/ReadWriteSplittingTests.java
wrapper/src/test/java/integration/refactored/host/TestEnvironment.java
wrapper/src/test/java/integration/util/AuroraTestUtility.java
wrapper/src/test/java/software/amazon/jdbc/plugin/failover/ClusterAwareReaderFailoverHandlerTest.java
wrapper/src/test/java/software/amazon/jdbc/plugin/failover/ClusterAwareWriterFailoverHandlerTest.java
wrapper/src/test/resources/logging-test.properties

Upgrade AWS SDK
Fix AuroraPgDialect detect logic
@karenc-bq

fix dialect detection logic

---

wrapper/src/main/java/software/amazon/jdbc/DataSourceConnectionProvider.java
wrapper/src/main/java/software/amazon/jdbc/dialect/AuroraMysqlDialect.java
wrapper/src/main/java/software/amazon/jdbc/dialect/AuroraPgDialect.java
wrapper/src/main/java/software/amazon/jdbc/dialect/DialectManager.java
wrapper/src/main/java/software/amazon/jdbc/dialect/RdsPgDialect.java
wrapper/src/main/java/software/amazon/jdbc/ds/AwsWrapperDataSource.java
wrapper/src/main/java/software/amazon/jdbc/util/PropertyUtils.java
wrapper/src/test/java/integration/refactored/container/tests/AuroraFailoverTest.java
wrapper/src/test/java/integration/refactored/container/tests/DataSourceTests.java

Fix Data Source flaky tests
@karenc-bq 
@aaron-congo

fix Data Source flaky tests

---

CHANGELOG.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

Update versioning and changelog for upcoming 2.0.0 release.

Update versioning and changelog

---

CHANGELOG.md

Update CHANGELOG with internal connection pool details

---

benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

chore: increase versioning to 2.1.0

---

CHANGELOG.md

doc: address comments for the changelog

---

CHANGELOG.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

Update changelog and versioning for 2.1.1 release.

chore: update changelog and versioning

---

README.md
docs/development-guide/IntegrationTests.md

Add list of Aurora PostgreSQL versions that have been tested

docs: add list of Aurora PostgreSQL versions that have been tested

---

docs/Documentation.md

doc: link performance tests in table of contents

---

docs/using-the-jdbc-driver/using-plugins/UsingTheReadWriteSplittingPlugin.md

docs: document the leastConnections strategy for internal pools

---

build.gradle.kts
gradle.properties

chore: set nexus.publish to false by default

---

CHANGELOG.md

Fix CHANGELOG link to `TargetDriverDialects.md`

Fix CHANGELOG link to TargetDriverDialects.md

---

examples/HikariExample/src/main/java/software/amazon/HikariFailoverExample.java

Correct portNumber to serverPort in Hikari example
Addresses #503.

docs: correct portNumber to serverPort in Hikari example

---

Maintenance.md

This is up for discussion and should not be considered final.
Maintenance and release policy
Added Maintenance.md

docs: Initial pass at a maintenance and release policy.

---

Maintenance.md

doc: update maintenance page

---

CHANGELOG.md
README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md

@karenc-bq @crystall-bitquill @hsuamz @congoamz @sergiyv-improving @davecramer

doc: update documentation for MySQL JDBC release

---

CHANGELOG.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md

doc: migration guide

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringWildflyExample/README.md
examples/SpringWildflyExample/wildfly/modules/software/amazon/jdbc/main/module.xml
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

chore: update changelog and versioning for version 2.2.2

---

.github/workflows/dependabot-auto-merge.yml

Auto-approve PR by dependabot for minor/patch version updates
@karenc-bq

dependabot auto approval

---

.github/workflows/dependabot-auto-merge.yml

Dependabot auto approval
@karenc-bq

Dependabot auto merge

---

examples/AWSDriverExample/src/main/java/software/amazon/AwsIamAuthenticationDatasourceExample.java
examples/AWSDriverExample/src/main/java/software/amazon/AwsSecretsManagerConnectionPluginMySQLExample.java
examples/AWSDriverExample/src/main/java/software/amazon/ReadWriteSplittingMySQLExample.java
examples/AWSDriverExample/src/main/java/software/amazon/ReadWriteSplittingSpringJdbcTemplateMySQLExample.java
examples/AWSDriverExample/src/main/java/software/amazon/ReadWriteSplittingSpringJdbcTemplatePostgresExample.java

Add MySQL-specific sample code for existing PostgreSQL sample code in the `examples` directory.

docs: add MySQL sample code

---

wrapper/src/test/java/integration/host/TestEnvironment.java
wrapper/src/test/java/integration/host/TestEnvironmentConfiguration.java
wrapper/src/test/java/integration/host/TestEnvironmentProvider.java

Refactor integration tests configuration.
@karenc-bq @aaron-congo @aaronchung-bitquill @crystall-bitquill

chore: refactor integration tests configuration

---

wrapper/src/main/java/software/amazon/jdbc/Driver.java
wrapper/src/main/resources/messages.properties

Ensure error message mentions that the target drivers need to be registered.

chore: update error message

---

.github/workflows/dependabot-auto-merge.yml

change branch pattern for dependabot automerge

change branch pattern for dependabot automerge

---

examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringWildflyExample/README.md
examples/VertxExample/README.md
examples/VertxExample/build.gradle.kts
examples/VertxExample/gradle.properties
examples/VertxExample/src/main/java/com/example/starter/MainVerticle.java
examples/VertxExample/src/main/java/com/example/starter/model/Example.java
examples/VertxExample/src/main/java/com/example/starter/model/Instance.java
settings.gradle.kts
wrapper/src/main/java/software/amazon/jdbc/Driver.java

Sample code for using the driver with Vert.x

docs: vert.x example

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringWildflyExample/README.md
examples/SpringWildflyExample/wildfly/modules/software/amazon/jdbc/main/module.xml
examples/VertxExample/README.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

Update versioning and changelog for  version 2.2.3

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringWildflyExample/README.md
examples/VertxExample/README.md

Change version to 2.2.2 in documentation
Addresses #574

docs: change version to 2.2.2

---

README.md

rewrite README.md
Updated and reworded main README page
@karenc-bq @hsuamz @sergiyvamz

doc: rewrite README.md

---

wrapper/src/main/java/software/amazon/jdbc/plugin/failover/FailoverConnectionPlugin.java
wrapper/src/main/java/software/amazon/jdbc/plugin/staledns/AuroraStaleDnsPlugin.java
wrapper/src/test/java/integration/container/tests/ReadWriteSplittingTests.java
wrapper/src/test/java/software/amazon/jdbc/plugin/failover/FailoverConnectionPluginTest.java

Integration test: https://github.com/Bit-Quill/aws-advanced-jdbc-wrapper/actions/runs/5697184986

fix: remove static provider check

---

.github/workflows/code_quality.yml
.github/workflows/main.yml
.github/workflows/run-hibernate-orm-tests.yml
.github/workflows/run-standard-integration-tests.yml

Check and skip required checks for doc changes

chore: run required checks for docs

---

.github/workflows/code_quality.yml
.github/workflows/main.yml
.github/workflows/run-hibernate-orm-tests.yml
.github/workflows/run-standard-integration-tests.yml

chore: fix conditions

---

.github/workflows/code_quality.yml
.github/workflows/main.yml
.github/workflows/run-hibernate-orm-tests.yml
.github/workflows/run-standard-integration-tests.yml

chore: check files changed

---

Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringWildflyExample/README.md
examples/VertxExample/README.md

@sergiyv-improving @hsuamz @karenc-bq @crystall-bitquill

docs: update version to 2.2.3

---

docs/KnownLimitations.md

Clarify limitations with Blue/Green deployments

Clarify limitations with Blue/Green deployments

---

docs/using-the-jdbc-driver/using-plugins/UsingTheReadWriteSplittingPlugin.md
wrapper/src/test/java/integration/container/tests/AutoscalingTests.java
wrapper/src/test/java/integration/container/tests/ReadWriteSplittingTests.java

Integration test run: https://github.com/Bit-Quill/aws-advanced-jdbc-wrapper/actions/runs/5802237467

chore: remove unnecessary aurora host list provider plugin configuration

---

ADOPTERS.md

added ADOPTERS.md

---

README.md

doc: fix typos

---

.github/workflows/run-autoscaling-tests.yml
wrapper/src/test/java/integration/container/tests/AuroraFailoverTest.java

test: disable autoscaling on push to main and fix test_failFromWriterWhereKeepSessionStateOnFailoverIsTrue

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringTxFailoverExample/README.md
examples/SpringWildflyExample/README.md
examples/SpringWildflyExample/wildfly/modules/software/amazon/jdbc/main/module.xml
examples/VertxExample/README.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

Update changelog and versioning for 2.2.5
To be merged once 2.2.5 has been released.

chore: update changelog and versioning for 2.2.5

---

README.md

Update known limitations with global databases
Related to #689

docs: update known limitations with global databases

---

wrapper/build.gradle.kts
wrapper/src/test/java/software/amazon/jdbc/plugin/efm/MultiThreadedMonitorThreadContainerTest.java

chore: update aws sdk dependency versions

---

wrapper/src/main/java/software/amazon/jdbc/dialect/AuroraMysqlDialect.java
wrapper/src/main/java/software/amazon/jdbc/dialect/DialectCodes.java
wrapper/src/main/java/software/amazon/jdbc/dialect/DialectManager.java
wrapper/src/main/java/software/amazon/jdbc/dialect/MysqlDialect.java
wrapper/src/main/java/software/amazon/jdbc/dialect/PgDialect.java
wrapper/src/main/java/software/amazon/jdbc/dialect/RdsMultiAzDbClusterMysqlDialect.java
wrapper/src/main/java/software/amazon/jdbc/dialect/RdsMultiAzDbClusterPgDialect.java
wrapper/src/main/java/software/amazon/jdbc/dialect/UnknownDialect.java
wrapper/src/main/java/software/amazon/jdbc/exceptions/AbstractPgExceptionHandler.java
wrapper/src/main/java/software/amazon/jdbc/exceptions/MultiAzDbClusterPgExceptionHandler.java
wrapper/src/main/java/software/amazon/jdbc/exceptions/PgExceptionHandler.java
wrapper/src/main/java/software/amazon/jdbc/hostlistprovider/RdsMultiAzDbClusterListProvider.java
wrapper/src/main/java/software/amazon/jdbc/plugin/AuroraConnectionTrackerPlugin.java
wrapper/src/test/java/software/amazon/jdbc/hostlistprovider/RdsMultiAzDbClusterListProviderTest.java
wrapper/src/test/java/software/amazon/jdbc/plugin/AuroraConnectionTrackerPluginTest.java

This CR is to add support for AWS RDS Multi-AZ DB Cluster, both MySQL and Postgres.

Add support for AWS RDS Multi-AZ DB Cluster, MySQL and Postgres.

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringTxFailoverExample/README.md
examples/SpringWildflyExample/README.md
examples/SpringWildflyExample/wildfly/modules/software/amazon/jdbc/main/module.xml
examples/VertxExample/README.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

[](chore: update changelog and versioning for 2.3.0)
@karenc-bq 
@sergiyv-improving

chore: update changelog and versioning for 2.3.0

---

CHANGELOG.md

Add changes related to AWS RDS Multi-AZ DB Cluster in CHANGELOG.md

chore: add changes related to AWS RDS Multi-AZ DB Cluster in CHANGELOG.md

---

wrapper/src/main/java/software/amazon/jdbc/plugin/efm/MonitorImpl.java

Log intentionally ignored exceptions in FINEST log levels instead of warning.

chore: reduce log level for intentionally ignored exceptions

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringTxFailoverExample/README.md
examples/SpringWildflyExample/README.md
examples/SpringWildflyExample/wildfly/modules/software/amazon/jdbc/main/module.xml
examples/VertxExample/README.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

Update changelog and versioning for version 2.3.1

chore: update changelog and versioning for version 2.3.1

---

wrapper/src/main/java/software/amazon/jdbc/HostSpec.java
wrapper/src/main/java/software/amazon/jdbc/HostSpecBuilder.java
wrapper/src/main/java/software/amazon/jdbc/util/ConnectionUrlParser.java
wrapper/src/main/java/software/amazon/jdbc/util/RdsUtils.java

Set HostId in HostSpec in case of Aurora instance endpoint.
@karenc-bq 
@brunos-bq

set hostId in HostSpec

---

wrapper/src/main/java/software/amazon/jdbc/ConnectionPluginChainBuilder.java
wrapper/src/main/java/software/amazon/jdbc/ConnectionPluginManager.java

Expose AuroraInitialConnectionStrategyPlugin with a plugin code
@karenc-bq 
@brunos-bq

Fix: expose AuroraInitialConnectionStrategyPlugin with a plugin code

---

wrapper/src/main/java/software/amazon/jdbc/authentication/AwsCredentialsManager.java

chore: replace synchronized with locks in AwsCredentialsManager
issue #783 
@sergiyv-improving 
@karenc-bq

chore: replace synchronized with locks in AwsCredentialsManager

---

wrapper/src/main/java/software/amazon/jdbc/plugin/efm2/MonitorImpl.java

Improve efm2 plugin failure detection timing.
- Verify that both queues are empty when Monitor is going to be disposed.
- Take into account a time spent on checking connection status and do a shorter thread sleep.
@karenc-bq 
@aaron-congo 
@brunos-bq

Improve efm2 failure detection timing

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringTxFailoverExample/README.md
examples/SpringWildflyExample/README.md
examples/SpringWildflyExample/wildfly/modules/software/amazon/jdbc/main/module.xml
examples/VertxExample/README.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

Update changelog and versioning for version 2.3.2 release.

chore: update versioning and changelog

---

wrapper/src/main/java/software/amazon/jdbc/hostlistprovider/RdsHostListProvider.java

fix: making a variable volatile in RdsHostListProvider
issue #486

fix: making a variable volatile in RdsHostListProvider

---

aws-advanced-jdbc-wrapper-bundle/build.gradle.kts
aws-advanced-jdbc-wrapper-bundle/gradle.properties
settings.gradle.kts
src/main/resources/META-INF/services/java.sql.Driver
wrapper/build.gradle.kts
wrapper/src/main/java/software/amazon/jdbc/plugin/federatedauth/FederatedAuthPlugin.java

Add new task to create an uber jar containing the dependencies for federated authentication plugin
Added new module to keep bundling and shadowing logic separate from the main gradle scripts.

feat: federated uber jar

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringTxFailoverExample/README.md
examples/SpringWildflyExample/README.md
examples/SpringWildflyExample/wildfly/modules/software/amazon/jdbc/main/module.xml
examples/VertxExample/README.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

chore: update versioning and changelog for release version 2.3.3
chore: update versioning and changelog for release version 2.3.3

chore: update versioning and changelog for release version 2.3.3

---

.github/workflows/maven_release.yml
.github/workflows/maven_snapshot.yml
.github/workflows/release_draft.yml
aws-advanced-jdbc-wrapper-bundle/build.gradle.kts

update draft, snapshot, and release workflow files
update draft, snapshot, and release workflow files

update draft, snapshot, and release workflow files

---

wrapper/src/main/java/software/amazon/jdbc/hostlistprovider/ConnectionStringHostListProvider.java
wrapper/src/main/java/software/amazon/jdbc/wrapper/ConnectionWrapper.java
wrapper/src/test/java/integration/container/tests/ReadWriteSplittingTests.java

resolve TODOs in the codebase
Removed some TODOs that were no longer relevant. Resolved small SQL change.

chore: resolve TODOs in the codebase

---

.github/workflows/code_quality.yml
.github/workflows/main.yml
.github/workflows/maven_release.yml
.github/workflows/maven_snapshot.yml
.github/workflows/mysql_advanced_performance.yml
.github/workflows/mysql_performance.yml
.github/workflows/pg_advanced_performance.yml
.github/workflows/pg_performance.yml
.github/workflows/release_draft.yml
.github/workflows/run-autoscaling-tests.yml
.github/workflows/run-hibernate-orm-tests.yml
.github/workflows/run-integration-tests.yml
.github/workflows/run-standard-integration-tests.yml

Updated GitHub Actions that are now deprecated
Updated action versions to latest

chore: update github actions

---

wrapper/src/main/java/software/amazon/jdbc/plugin/efm/MonitorImpl.java
wrapper/src/main/java/software/amazon/jdbc/plugin/efm2/MonitorImpl.java
wrapper/src/main/java/software/amazon/jdbc/util/telemetry/OpenTelemetryContext.java
wrapper/src/main/java/software/amazon/jdbc/util/telemetry/OpenTelemetryFactory.java
wrapper/src/main/java/software/amazon/jdbc/util/telemetry/XRayTelemetryContext.java
wrapper/src/main/resources/aws_advanced_jdbc_wrapper_messages.properties

bug: EFM telemetry data not being submitted to X-Ray
Telemetry trace associated with entire monitoring thread removed since traces for long-running tasks are considered anti-pattern. 
@karenc-bq 

bug: EFM telemetry data not being submitted to X-Ray

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringTxFailoverExample/README.md
examples/SpringWildflyExample/README.md
examples/SpringWildflyExample/wildfly/modules/software/amazon/jdbc/main/module.xml
examples/VertxExample/README.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

chore: changelog and changelog for release version 2.3.4

---

CHANGELOG.md
examples/DBCPExample/build.gradle.kts
examples/DBCPExample/gradle.properties
examples/DBCPExample/src/main/java/software/amazon/DBCPIamExample.java
examples/DBCPExample/src/main/java/software/amazon/DBCPSimpleExample.java
settings.gradle.kts

Adding sample code configuring the wrapper with DBCP

docs: sample code for DBCP

---

wrapper/build.gradle.kts
wrapper/src/test/java/integration/container/tests/ReadWriteSplittingTests.java

test: enable tests against mysql

---

docs/using-the-jdbc-driver/UsingTheJdbcDriver.md

Update logging section to include instructions for Spring

docs: update logging instructions

---

docs/using-the-jdbc-driver/Telemetry.md

Update telemetry documentation

docs: update telemetry documentation

---

.github/workflows/run-integration-tests-codebuild.yml
wrapper/src/test/java/integration/TestEnvironmentInfo.java
wrapper/src/test/java/integration/container/TestDriverProvider.java
wrapper/src/test/java/integration/container/TestEnvironment.java
wrapper/src/test/java/integration/container/tests/AdvancedPerformanceTest.java
wrapper/src/test/java/integration/container/tests/AuroraFailoverTest.java
wrapper/src/test/java/integration/container/tests/AutoscalingTests.java
wrapper/src/test/java/integration/container/tests/AwsIamIntegrationTest.java
wrapper/src/test/java/integration/container/tests/ReadWriteSplittingTests.java
wrapper/src/test/java/integration/host/TestEnvironment.java
wrapper/src/test/java/integration/host/TestEnvironmentConfiguration.java
wrapper/src/test/java/integration/util/AuroraTestUtility.java

Added a new workflow using a self-hosted runner spun up by AWS Codebuild.
Allows overriding the RDS Endpoint in AWS RDS SDK clients.

chore: add manual workflow testing with codebuild

---

wrapper/src/main/java/software/amazon/jdbc/profile/ConfigurationProfilePresetCodes.java

fix issue initializing Configuration Profile codes
https://github.com/aws/aws-advanced-jdbc-wrapper/issues/1000
@karenc-bq 

fix issue initializing Configuration Profile codes

---

.github/workflows/mysql_advanced_performance.yml
.github/workflows/mysql_performance.yml
.github/workflows/pg_advanced_performance.yml
.github/workflows/pg_performance.yml
.github/workflows/run-integration-tests-codebuild.yml
.github/workflows/run-integration-tests-latest.yml
.github/workflows/run-integration-tests-lts.yml
examples/AWSDriverExample/src/main/java/software/amazon/PgConnectionSample.java

Rename integration test environment variable from AURORA_DB_REGION to RDS_DB_REGION

chore: rename AURORA_DB_REGION to RDS_DB_REGION

---

docs/using-the-jdbc-driver/using-plugins/UsingTheOktaAuthPlugin.md
examples/AWSDriverExample/src/main/java/software/amazon/PgConnectionSample.java

- fix incorrect reference to federated auth plugin in the okta documentation

docs: fix incorrect reference to federated auth plugin

---

README.md

doc: add section in Known Limitations about Virtual Threading pinning
doc: add section in Known Limitations about Virtual Threading pinning
Addresses https://github.com/aws/aws-advanced-jdbc-wrapper/issues/1024

doc: add section in Known Limitations about Virtual Threading pinning

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
docs/using-the-jdbc-driver/using-plugins/UsingTheFederatedAuthPlugin.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringTxFailoverExample/README.md
examples/SpringWildflyExample/README.md
examples/SpringWildflyExample/wildfly/modules/software/amazon/jdbc/main/module.xml
examples/VertxExample/README.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

chore: bump driver version and update changelog
chore: bump driver version and update changelog

chore: bump driver version and update changelog

---

docs/using-the-jdbc-driver/using-plugins/UsingTheFailoverPlugin.md

Adds additional clarification and limitations in regards to Blue/Green.

docs: clarify blue/green support and limitations

---

CHANGELOG.md
wrapper/src/main/java/software/amazon/jdbc/states/SessionStateServiceImpl.java

Avoid setting a blank catalog when connection is closing.
Addresses: #1042
@karenc-bq 

fix: avoid setting a blank catalog

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
docs/using-the-jdbc-driver/using-plugins/UsingTheFederatedAuthPlugin.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringTxFailoverExample/README.md
examples/SpringWildflyExample/README.md
examples/SpringWildflyExample/wildfly/modules/software/amazon/jdbc/main/module.xml
examples/VertxExample/README.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

chore: bump version

---

docs/using-the-jdbc-driver/using-plugins/UsingTheOktaAuthPlugin.md

Update Okta documentation to include missing required dependency

docs: add required dependencies for Okta

---

docs/using-the-jdbc-driver/DataSource.md

Add note about HikariCP's log messages, related to #1049

docs: add note about HikariCP's instantiation failure messages

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
docs/using-the-jdbc-driver/using-plugins/UsingTheFederatedAuthPlugin.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringTxFailoverExample/README.md
examples/SpringWildflyExample/README.md
examples/SpringWildflyExample/wildfly/modules/software/amazon/jdbc/main/module.xml
examples/VertxExample/README.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

chore: update changelog and versioning for 2.3.9

chore: update changelog and versioning for 2.3.9

---

wrapper/src/main/java/software/amazon/jdbc/HikariPooledConnectionProvider.java

Make private members protected to facilitate its extensibility.
@karenc-bq 
@aaron-congo 

make private members protected

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
docs/using-the-jdbc-driver/using-plugins/UsingTheFederatedAuthPlugin.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringTxFailoverExample/README.md
examples/SpringWildflyExample/README.md
examples/SpringWildflyExample/wildfly/modules/software/amazon/jdbc/main/module.xml
examples/VertxExample/README.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

chore: update changelog and bump version for 2.4.0

---

wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessConnectionPlugin.java
wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterMonitor.java
wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterMonitorInitializer.java
wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterServiceImpl.java
wrapper/src/main/java/software/amazon/jdbc/util/RdsUrlType.java
wrapper/src/main/resources/aws_advanced_jdbc_wrapper_messages.properties
wrapper/src/test/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterServiceImplTest.java

fix: limitless plugin - add null checks

---

docs/using-the-jdbc-driver/using-plugins/UsingTheCustomEndpointPlugin.md
wrapper/src/main/java/software/amazon/jdbc/plugin/customendpoint/CustomEndpointPlugin.java

Add documentation for the custom endpoint plugin

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
docs/using-the-jdbc-driver/using-plugins/UsingTheFederatedAuthPlugin.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringTxFailoverExample/README.md
examples/SpringWildflyExample/README.md
examples/SpringWildflyExample/wildfly/modules/software/amazon/jdbc/main/module.xml
examples/VertxExample/README.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

chore: update changelog and bump version for 2.5.1

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
docs/using-the-jdbc-driver/using-plugins/UsingTheFederatedAuthPlugin.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringTxFailoverExample/README.md
examples/SpringWildflyExample/README.md
examples/SpringWildflyExample/wildfly/modules/software/amazon/jdbc/main/module.xml
examples/VertxExample/README.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

update changelog and bump version for 2.5.2

---

wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessConnectionPlugin.java
wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterServiceImpl.java

fix: limitless various minor fixes

---

wrapper/src/main/java/software/amazon/jdbc/Driver.java
wrapper/src/main/java/software/amazon/jdbc/util/RdsUtils.java
wrapper/src/test/java/integration/container/TestEnvironment.java
wrapper/src/test/java/software/amazon/jdbc/util/RdsUtilsTests.java

Allow user to specify a function that rewrites host names.
https://github.com/orgs/awslabs/projects/91/views/1?pane=issue&itemId=79962076
@karenc-bq 
@aaron-congo

allow user to specify a function that rewrites host names

---

wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterMonitor.java
wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterServiceImpl.java
wrapper/src/main/java/software/amazon/jdbc/util/SlidingExpirationCache.java

fix: SlidingExpirationCache#put cache item expiration

---

wrapper/src/main/java/software/amazon/jdbc/plugin/failover/FailoverConnectionPlugin.java
wrapper/src/main/java/software/amazon/jdbc/plugin/failover2/FailoverConnectionPlugin.java

https://github.com/aws/aws-advanced-jdbc-wrapper/issues/1199
@karenc-bq 
@aaron-congo

fix failover mode initialization

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
docs/using-the-jdbc-driver/using-plugins/UsingTheFederatedAuthPlugin.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringTxFailoverExample/README.md
examples/SpringWildflyExample/README.md
examples/SpringWildflyExample/wildfly/modules/software/amazon/jdbc/main/module.xml
examples/VertxExample/README.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

Update changelog and bump version for 2.5.3

---

wrapper/src/test/java/integration/container/TestDriverProvider.java

Clear tracked connections before each integration test.
@karenc-bq 
@aaron-congo 

chore: clear tracked connections before each integration test

---

wrapper/src/main/java/software/amazon/jdbc/plugin/OpenedConnectionTracker.java

Remove closed connections by Hikari CP from tracked connections
@karenc-bq 
@aaron-congo 

chore: remove closed connections by Hikari CP from tracked connections

---

examples/AWSDriverExample/src/main/java/software/amazon/ReadWriteSplittingMySQLExample.java

Fix incorrect example port

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
docs/using-the-jdbc-driver/using-plugins/UsingTheFederatedAuthPlugin.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringTxFailoverExample/README.md
examples/SpringWildflyExample/README.md
examples/SpringWildflyExample/wildfly/modules/software/amazon/jdbc/main/module.xml
examples/VertxExample/README.md
gradle.properties
wrapper/build.gradle.kts
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

Update changelog and bump version for 2.5.4
Update changelog and bump version for 2.5.4
Also upped versions for sts and rds that were mismatched.

Update changelog and bump version for 2.5.4

---

benchmarks/src/jmh/java/software/amazon/jdbc/benchmarks/PluginBenchmarks.java
docs/development-guide/Pipelines.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
docs/using-the-jdbc-driver/using-plugins/UsingTheReadWriteSplittingPlugin.md
examples/AWSDriverExample/build.gradle.kts
examples/AWSDriverExample/src/main/java/software/amazon/InternalConnectionPoolPasswordWarning.java
examples/AWSDriverExample/src/main/java/software/amazon/ReadWriteSplittingMySQLExample.java
examples/AWSDriverExample/src/main/java/software/amazon/ReadWriteSplittingPostgresExample.java
examples/ReadWriteSplittingSample/src/main/java/software/amazon/ReadWriteSplittingSample.java
wrapper/src/main/java/software/amazon/jdbc/ConnectionPlugin.java
wrapper/src/main/java/software/amazon/jdbc/ConnectionPluginManager.java
wrapper/src/main/java/software/amazon/jdbc/ConnectionProviderManager.java
wrapper/src/main/java/software/amazon/jdbc/HikariPooledConnectionProvider.java
wrapper/src/main/java/software/amazon/jdbc/PluginService.java
wrapper/src/main/java/software/amazon/jdbc/targetdriverdialect/TargetDriverDialectManager.java
wrapper/src/test/java/integration/container/TestDriverProvider.java
wrapper/src/test/java/integration/container/tests/AutoscalingTests.java
wrapper/src/test/java/integration/container/tests/ReadWriteSplittingPerformanceTest.java
wrapper/src/test/java/integration/container/tests/ReadWriteSplittingTests.java

chore: update deprecated ConnectionProviderManager function calls

---

examples/SpringHibernateExample/README.md

Fixes #1266 
Fix indentations.

Fix [#1266]

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
docs/using-the-jdbc-driver/using-plugins/UsingTheFederatedAuthPlugin.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringTxFailoverExample/README.md
examples/SpringWildflyExample/README.md
examples/VertxExample/README.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

Update changelog and bump version for 2.5.5

---

examples/AWSDriverExample/build.gradle.kts
examples/AWSDriverExample/src/main/java/software/amazon/C3P0Example.java
examples/AWSDriverExample/src/main/resources/logging-example.properties
wrapper/build.gradle.kts
wrapper/src/main/java/software/amazon/jdbc/C3P0PooledConnectionProvider.java
wrapper/src/main/java/software/amazon/jdbc/RoundRobinHostSelector.java

Add c3p0 pooling to the driver. Provides an example and a corresponding connection provider class.
@karenc-bq 
@aaron-congo

C3p0 example

---

Maintenance.md

Fix Maintenance Markdown Release Version Number
See Title

doc: fix release ver num

---

wrapper/src/main/java/software/amazon/jdbc/ConnectionPluginManager.java
wrapper/src/main/java/software/amazon/jdbc/PluginServiceImpl.java
wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessConnectionContext.java
wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterServiceImpl.java
wrapper/src/test/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterServiceImplTest.java

Fix leaked connection in Limitless plugin.
@karenc-bq 

fix leaked connection in Limitless plugin

---

wrapper/src/main/java/software/amazon/jdbc/plugin/federatedauth/OktaAuthPluginFactory.java
wrapper/src/test/java/software/amazon/jdbc/ConnectionPluginManagerTests.java

fix codestyle

---

wrapper/src/main/java/software/amazon/jdbc/dialect/AuroraMysqlDialect.java
wrapper/src/main/java/software/amazon/jdbc/dialect/AuroraPgDialect.java
wrapper/src/main/java/software/amazon/jdbc/dialect/RdsMultiAzDbClusterMysqlDialect.java
wrapper/src/main/java/software/amazon/jdbc/dialect/RdsMultiAzDbClusterPgDialect.java
wrapper/src/main/java/software/amazon/jdbc/plugin/bluegreen/routing/SubstituteConnectRouting.java
wrapper/src/main/java/software/amazon/jdbc/util/RdsUtils.java
wrapper/src/test/java/integration/util/AuroraTestUtility.java

refactor: simplify checks to see if a plugin is used

---

CHANGELOG.md
Maintenance.md
benchmarks/README.md
docs/GettingStarted.md
docs/using-the-jdbc-driver/UsingTheJdbcDriver.md
docs/using-the-jdbc-driver/using-plugins/UsingTheFederatedAuthPlugin.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringTxFailoverExample/README.md
examples/SpringWildflyExample/README.md
examples/SpringWildflyExample/wildfly/modules/software/amazon/jdbc/main/module.xml
examples/VertxExample/README.md
gradle.properties
wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
wrapper/src/test/resources/hibernate_files/java-module.gradle

Update changelog and bump version for 2.6.0

chore: update CHANGELOG.md and driver version to 2.6.0

---

.github/workflows/run-hibernate-orm-tests.yml

Avoid running hibernate tests for every build
@karenc-bq

chore: avoid running hibernate tests for every build

---

.github/workflows/maven_release.yml
CHANGELOG.md
Maintenance.md
benchmarks/README.md
build.gradle.kts
docs/GettingStarted.md
docs/using-the-jdbc-driver/using-plugins/UsingTheFederatedAuthPlugin.md
examples/SpringBootHikariExample/README.md
examples/SpringHibernateExample/README.md
examples/SpringTxFailoverExample/README.md
examples/SpringWildflyExample/README.md
examples/SpringWildflyExample/wildfly/modules/software/amazon/jdbc/main/module.xml
examples/VertxExample/README.md
gradle.properties

chore: update changelog and bump version to 2.6.1

---

wrapper/src/test/java/integration/container/tests/BlueGreenDeploymentTests.java

test: clarify pass criteria for b/g test

---

README.md

chore: fix broken badge links

---

README.md

Removes outdated portions of the documentation related to BG.

docs: removing outdated information regarding blue/green support
