aws/aws-advanced-jdbc-wrapper

docs/using-the-jdbc-driver/DataSource.md, docs/using-the-jdbc-driver/sample-code/HikariSample.java
HikariCP documentation improvements
I tried setting up the driver and ran into some issues following the docs. I don't know how HikariCP works that well so it took me a couple hours to understand what was intended. 
What threw me off was that this [file](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/sample-code/HikariSample.java#L52) simply doesn't compile for a few reasons
* Its missing imports
* Its calling a method on a `HikariDataSource` that simply doesn't exist. 
I have updated it to configure the target data source properties correctly so they will be correctly configured on the AWS wrapper data source using [reflection](https://github.com/openbouquet/HikariCP/blob/master/src/main/java/com/zaxxer/hikari/util/PropertyElf.java).
=> HikariCP documentation improvements

wrapper/src/main/java/software/amazon/jdbc/hostlistprovider/AuroraHostListProvider.java
Modify the queries used by MySQL and PostgreSQL to query topologies so they are more consistent
=> refactor: make topology queries more consistent between different databases

wrapper/src/main/java/software/amazon/jdbc/plugin/failover/ClusterAwareWriterFailoverHandler.java
RDS-1199: Fix bug where failoverTimeoutMs was not obeyed
- Before this commit, failover could take up to two times the length of
failoverTimeoutMs before giving up. This commit adds changes to
limit failover to run for a maximum of failoverTimeoutMs
milliseconds
@karenc-bq 
@congoamz
=> Fix bug where failoverTimeoutMs was not obeyed

wrapper/src/test/java/integration/container/aurora/mysql/mariadbdriver/AuroraMysqlAwsIamIntegrationTest.java, wrapper/src/test/java/integration/container/aurora/mysql/mysqldriver/AuroraMysqlAwsIamIntegrationTest.java
Fix IAM integration tests that use IP addresses to establish connections.
@alecc-bq
=> test: fix failing IAM integration tests using IP addresses

wrapper/src/test/java/integration/container/aurora/mysql/AuroraMysqlBaseTest.java, wrapper/src/test/java/integration/container/aurora/mysql/mariadbdriver/AuroraMysqlReadWriteSplittingTest.java, wrapper/src/test/java/integration/container/aurora/mysql/mysqldriver/AuroraMysqlReadWriteSplittingTest.java, wrapper/src/test/java/integration/container/aurora/postgres/AuroraPostgresBaseTest.java, wrapper/src/test/java/integration/container/aurora/postgres/AuroraPostgresReadWriteSplittingTest.java, wrapper/src/test/java/integration/util/ContainerHelper.java
- This commit fixes a bug in the testing logic where some tests would fail after cluster failover because the cluster URL did not resolve to the new writer IP yet. These failures were flaky and seemed to only occur on GraalVM, likely due to the specific timing and DNS settings required to run into this problem
- After failover, the tests will now wait until the cluster URL resolves to the new writer IP before continuing with verification logic
- Also changed the GraalVM image to use java 8. Previously the image was using java 17
=> Fix cluster DNS resolution in testing logic

wrapper/src/test/java/integration/container/aurora/mysql/AuroraMysqlBaseTest.java
- the new value seemed to cause flaky test failures
=> Revert change to default mysql socket timeout

settings.gradle.kts, wrapper/build.gradle.kts, wrapper/src/main/java/software/amazon/jdbc/osgi/WrapperBundleActivator.java
RDS-1092
- Added dependencies
- Added bundle activator class
- Added headers for OSGi compatibility
=> OSGi compatibility

wrapper/src/main/java/software/amazon/jdbc/util/WrapperUtils.java
Fix runtime exceptions thrown as reported in #284 
In the original implementation the following exception gets thrown when retrieving a `PgArray` object 
```
Exception in thread "main" java.lang.RuntimeException: No wrapper class exists for 'org.postgresql.jdbc.PgArray'.
at software.amazon.jdbc.util.WrapperUtils.wrapWithProxyIfNeeded(WrapperUtils.java:270)
at software.amazon.jdbc.util.WrapperUtils.executeWithPlugins(WrapperUtils.java:230)
at software.amazon.jdbc.wrapper.ResultSetWrapper.getObject(ResultSetWrapper.java:708)
at com.zaxxer.hikari.pool.HikariProxyResultSet.getObject(HikariProxyResultSet.java)
at software.amazon.PG.getResult(PG.java:84)
at software.amazon.PG.main(PG.java:73)
```
This is because the class name passed to WrapperUtils is a database-specific implementation of the …
=> fix: runtime exception thrown for PgArray

docs/using-the-jdbc-driver/using-plugins/UsingTheReadWriteSplittingPlugin.md, wrapper/src/main/java/software/amazon/jdbc/plugin/DefaultConnectionPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/readwritesplitting/ReadWriteSplittingPlugin.java, wrapper/src/main/java/software/amazon/jdbc/util/SqlMethodAnalyzer.java, wrapper/src/test/java/software/amazon/jdbc/util/SqlMethodAnalyzerTest.java
- According to the Connection#setAutoCommit documentation, transactions are committed when autocommit is switched from false to true. This commit fixes a bug where inTransaction was not set to false when this occurred
=> Fix bug where inTransaction was not set to false when autocommit was switched from false to true

wrapper/src/main/java/software/amazon/jdbc/exceptions/PgExceptionHandler.java
Check for exception codes starting with "08" in PGExceptionHandler
@sergiyvamz
=> fix: add more connection exception codes for PostgreSQL exception handler

wrapper/src/main/java/software/amazon/jdbc/plugin/staledns/AuroraStaleDnsHelper.java, wrapper/src/main/java/software/amazon/jdbc/plugin/staledns/AuroraStaleDnsPlugin.java
fix: check whether the stale DNS plugin needs to do a force topology refresh
@sergiyvamz
=> fix: check whether the stale DNS plugin needs to do a force topology refresh

wrapper/src/main/java/software/amazon/jdbc/DataSourceConnectionProvider.java, wrapper/src/main/java/software/amazon/jdbc/PropertyDefinition.java, wrapper/src/test/java/integration/container/aurora/mysql/mysqldriver/AuroraMysqlAwsIamIntegrationTest.java, wrapper/src/test/java/software/amazon/jdbc/PropertyDefinitionTests.java
DataSourceConnectionProvider to not remove user/password properties on connect
This is to address https://github.com/awslabs/aws-advanced-jdbc-wrapper/issues/288
Changed PropertyDefinition removeAll() static method to removeAllExceptCredentials().
Updated DataSourceConnectionProvider to switch from removeAll() to removevAllExceptCredentials(). 
Added unit tests for PropertyDefinition
Added integration test to AuroraMysqlAwsIamIntegrationTest to test this case. 
@sergiyv-improving
=> fix: DataSourceConnectionProvider to not remove user/password properties on connect

wrapper/src/main/java/software/amazon/jdbc/PluginServiceImpl.java, wrapper/src/main/resources/messages.properties
Fix an incorrect log message in `PluginServiceImpl#setAvailability` that says host alias not found instead of empty hosts change list.
=> fix: incorrect log message for empty host change lists.

build.gradle.kts, wrapper/src/main/java/software/amazon/jdbc/wrapper/DatabaseMetaDataWrapper.java, wrapper/src/main/version/software/amazon/jdbc/util/DriverInfo.java
Return the correct Wrapper driver version when `DatabaseMetaData#get*Version()` is called.
When `DatabaseMetaData#get*Version()` is called, the wrapper incorrectly returned the target driver's version instead of its own version, e.g. 45.0.0 instead of 1.0.0.
This fix the version reporting as well as include the Git commit ID in the version.
The driver now reports: 
`Amazon Web Services (AWS) Advanced JDBC Wrapper 1.0.0 ( Revision: b49968339f99d7f97dda95815ec41bff264b2c72 )`
Test code:
```java
try (Connection conn = DriverManager.getConnection(CONNECTION_STRING, properties)) {
DatabaseMetaData metadata = conn.getMetaData();
String driverName = metadata.getDriverName();
String driverVersion = metadata.getDriverVersion();
int majorVersion = metadata.getDriverMajorVersion();
int minorVersion …
```
=> fix: report wrapper driver version with git commit id

wrapper/src/main/java/software/amazon/jdbc/plugin/AwsSecretsManagerConnectionPlugin.java, wrapper/src/test/java/software/amazon/jdbc/plugin/AwsSecretsManagerConnectionPluginTest.java
Close SecretsManagerClient to prevent leaking PoolingHttpClientConnectionManager.
AWSSecretsManagerPlugin creates a new SecretsManagerClient for each connection, which creates a new PoolingHttpClientConnectionManager. The driver never closes these SecretsManagerClient so as the user application runs on the number of PoolingHttpClientConnectionManager instances just keep climbing.
@joyc-bq 
=> fix: close aws secrets manager client

wrapper/src/main/java/software/amazon/jdbc/wrapper/ConnectionWrapper.java
fix: unwrap Savepoint objects when passing them in as parameters.
Fixes #328
`SavepointWrappper` objects are passed to `ConnectionWrapper#*rollback(final Savepoint savepoint)` as parameters, which are then passed to the target driver's rollback methods.
PGJDBC internally explicitly casts the Savepoint parameter to an internal object: https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java#L1836
```java
PSQLSavepoint pgSavepoint = (PSQLSavepoint) savepoint;
```
Since the driver passed in a `SavepointWrappper` object, this line in pgjdbc will throw a `ClassCastException`.
The only solution is to unwrap the Savepoint object before passing it in.
@joyc-bq 
=> fix: unwrap Savepoint objects when passing them in as parameters.

wrapper/src/main/java/software/amazon/jdbc/util/WrapperUtils.java
add null checks to WrapperUtils.getConnectionFromSqlObject()
Add null checks to WrapperUtils.getConnectionFromSqlObject()
Addresses issue https://github.com/awslabs/aws-advanced-jdbc-wrapper/issues/348
@karenc-bq
=> fix: add null checks to WrapperUtils.getConnectionFromSqlObject() (#348)

benchmarks/build.gradle.kts, wrapper/build.gradle.kts
Reverts awslabs/aws-advanced-jdbc-wrapper#335
Mockito 5 is not compatible with Java 8
=> Revert "chore(deps): bump org.mockito:mockito-inline from 4.8.0 to 5.1.1"

docs/using-the-jdbc-driver/UsingTheJdbcDriver.md, wrapper/src/main/java/software/amazon/jdbc/ConnectionPluginManager.java, wrapper/src/main/java/software/amazon/jdbc/util/ConnectionUrlParser.java, wrapper/src/test/java/integration/refactored/container/ConnectionStringHelper.java, wrapper/src/test/java/integration/refactored/container/tests/BasicConnectivityTests.java, wrapper/src/test/java/integration/refactored/container/tests/DataSourceTests.java, wrapper/src/test/java/integration/refactored/container/tests/HikariTests.java, wrapper/src/test/java/integration/refactored/container/tests/SpringTests.java, wrapper/src/test/java/software/amazon/jdbc/ConnectionPluginManagerTests.java
Set `auroraConnectionTracker`, `failover` and `efm` as the list of default connection plugins.
=> feat: default list of connection plugins

wrapper/src/main/java/software/amazon/jdbc/util/ConnectionUrlParser.java, wrapper/src/test/java/software/amazon/jdbc/util/ConnectionUrlParserTest.java
The `clusterInstanceHostPattern` parameter requires the following format "?.cluster.com", when setting the clusterInstanceHostPattern in the connection string, the extra question mark gets lost in the process, resulting an exception.
=> fix: ensure extra ? in the parameters do not get filtered out when parsing the URL

benchmarks/README.md, wrapper/src/main/java/software/amazon/jdbc/util/ConnectionUrlParser.java, wrapper/src/test/java/integration/refactored/container/tests/HikariTests.java, wrapper/src/test/java/software/amazon/jdbc/util/ConnectionUrlParserTest.java, wrapper/src/test/resources/hibernate_files/hibernate-core.gradle, wrapper/src/test/resources/hibernate_files/java-module.gradle
=> chore: update version for hibernate tests

wrapper/src/main/java/software/amazon/jdbc/hostlistprovider/AuroraHostListProvider.java, wrapper/src/main/java/software/amazon/jdbc/plugin/AuroraConnectionTrackerPlugin.java, wrapper/src/test/java/software/amazon/jdbc/plugin/AuroraConnectionTrackerPluginTest.java
Fetch the instance endpoint and add it to the host aliases for connections established using custom domains.
AuroraConnectionTrackerPlugin only looks up the instance endpoint for the current connection if the initial hostname is a cluster endpoint. 
If the connection is established via a custom domain or via the IP address, the AuroraConnectionTracker will not be able to track the opened connection since the tracker uses instance endpoints to track connections.
```
[2023-04-04 20:07:01.240150500] [FINEST ] software.amazon.jdbc.plugin.OpenedConnectionTracker populateOpenedConnectionQueue
[Internal Error] The driver is unable to track this opened connection because the instance endpoint is unknown. 
[2023-04-04 20:07:01.259151100] [FINEST ] …
```
=> fix: fetch instance endpoint to the host alias  for custom domains

docs/using-the-jdbc-driver/using-plugins/UsingTheAwsSecretsManagerPlugin.md, wrapper/src/main/java/software/amazon/jdbc/plugin/AwsSecretsManagerConnectionPlugin.java, wrapper/src/test/java/software/amazon/jdbc/plugin/AwsSecretsManagerConnectionPluginTest.java
Parse AWS Region if the secret ID provided to the Secrets Manager connection plugin is an ARN string, so that secretsManagerRegion is no longer a required parameter for ARNs.
Addresses #391
=> feat: parse region from ARN

wrapper/src/main/java/software/amazon/jdbc/plugin/failover/ClusterAwareReaderFailoverHandler.java, wrapper/src/test/java/integration/refactored/container/tests/AuroraFailoverTest.java, wrapper/src/test/resources/logging-test.properties
Add logs to flakey test so we can acquire more information when the test fails.
=> test: add logs to flakey test

wrapper/src/main/java/software/amazon/jdbc/plugin/readwritesplitting/ReadWriteSplittingPlugin.java, wrapper/src/test/java/integration/refactored/container/tests/ReadWriteSplittingTests.java
=> Include exception cause in applicable ReadWriteSplittingSQLExceptions

wrapper/src/main/java/software/amazon/jdbc/plugin/failover/FailoverConnectionPlugin.java
Remove logic that changes connection to a writer when setReadOnly(false) is called on reader connection.
https://github.com/awslabs/aws-advanced-jdbc-wrapper/issues/426
@karenc-bq 
@aaron-congo
=> Remove logic that changes connection to a writer

wrapper/build.gradle.kts, wrapper/src/main/java/software/amazon/jdbc/Driver.java, wrapper/src/main/java/software/amazon/jdbc/HostListProvider.java, wrapper/src/main/java/software/amazon/jdbc/HostSpec.java, wrapper/src/main/java/software/amazon/jdbc/PluginService.java, wrapper/src/main/java/software/amazon/jdbc/PluginServiceImpl.java, wrapper/src/main/java/software/amazon/jdbc/hostlistprovider/AuroraHostListProvider.java, wrapper/src/main/java/software/amazon/jdbc/hostlistprovider/ConnectionStringHostListProvider.java, wrapper/src/main/java/software/amazon/jdbc/plugin/AuroraConnectionTrackerPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/OpenedConnectionTracker.java, wrapper/src/main/java/software/amazon/jdbc/plugin/efm/HostMonitoringConnectionPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/efm/MonitorImpl.java, wrapper/src/main/java/software/amazon/jdbc/plugin/efm/MonitorServiceImpl.java, wrapper/src/main/resources/messages.properties, wrapper/src/test/build.gradle.kts, wrapper/src/test/java/software/amazon/jdbc/PluginServiceImplTests.java, wrapper/src/test/java/software/amazon/jdbc/hostlistprovider/AuroraHostListProviderTest.java, wrapper/src/test/java/software/amazon/jdbc/plugin/AuroraConnectionTrackerPluginTest.java, wrapper/src/test/java/software/amazon/jdbc/plugin/efm/ConcurrencyTests.java, wrapper/src/test/java/software/amazon/jdbc/plugin/efm/HostMonitoringConnectionPluginTest.java, wrapper/src/test/java/software/amazon/jdbc/plugin/efm/MonitorServiceImplTest.java, wrapper/src/test/java/software/amazon/jdbc/plugin/efm/MultiThreadedDefaultMonitorServiceTest.java, wrapper/src/test/java/software/amazon/jdbc/plugin/failover/FailoverConnectionPluginTest.java
https://github.com/Bit-Quill/aws-advanced-jdbc-wrapper/actions/runs/4920404497
1. After failover Aurora Connection Tracker incorrectly invalidates the newly promoted writer
2. After failover Aurora Connection Tracker incorrectly invalidates a random reader that is neither the old or new writer.
3. If the initial connection is established using an cluster endpoint, EFM plugin uses the cluster endpoint as the monitoring endpoint
Issue one is caused by the following check. 
```java
private boolean isRoleChanged(final EnumSet<NodeChangeOptions> changes) {
return changes.contains(NodeChangeOptions.PROMOTED_TO_WRITER)
|| changes.contains(NodeChangeOptions.PROMOTED_TO_READER);
}
```
We need to remove the check for `PROMOTED_TO_WRITER`
Issues 2 and 3 are both caused by missing or incorrect …
=> refactor: host alias logic in wrapper

docs/using-the-jdbc-driver/using-plugins/UsingTheReadWriteSplittingPlugin.md, examples/AWSDriverExample/src/main/java/software/amazon/ReadWriteSplittingPostgresExample.java, wrapper/src/main/java/software/amazon/jdbc/HikariPooledConnectionProvider.java, wrapper/src/test/java/integration/refactored/container/tests/ReadWriteSplittingTests.java, wrapper/src/test/java/integration/util/AuroraTestUtility.java, wrapper/src/test/java/software/amazon/jdbc/HikariPooledConnectionProviderTest.java
=> Improve internal connection pool key defaults

wrapper/src/main/java/software/amazon/jdbc/HostSpec.java, wrapper/src/main/java/software/amazon/jdbc/dialect/AuroraMysqlDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/AuroraPgDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/TopologyAwareDatabaseCluster.java, wrapper/src/main/java/software/amazon/jdbc/hostlistprovider/AuroraHostListProvider.java, wrapper/src/main/java/software/amazon/jdbc/plugin/failover/FailoverConnectionPlugin.java, wrapper/src/test/java/software/amazon/jdbc/hostlistprovider/AuroraHostListProviderTest.java
Remove the isMultiWriterCluster flag from the AuroraTopologyService and add checks for stale topology records.
Multi writer clusters are not longer supported, so the isMultiWriterCluster flag that was used to disable failover has been removed. Additionally, checks have been added to ensure stale writer records that are obtained post writer-failover are not being used.
=> Remove isMultiWriterCluster flag and ignore stale records when querying the topology

CHANGELOG.md
@karenc-bq @congoamz @sergiyv-improving
=> Update CHANGELOG for 2.1.0

wrapper/src/main/java/software/amazon/jdbc/hostlistprovider/AuroraHostListProvider.java
fix: generalize WrongArgumentException to Exception
Fixes https://github.com/awslabs/aws-advanced-jdbc-wrapper/issues/444.
=> fix: generalize WrongArgumentException to Exception

config/checkstyle/checkstyle-suppressions.xml, config/checkstyle/google_checks.xml, wrapper/build.gradle.kts
Add Illegal Import check for driver-specific imports.
If a new file adds `com.mysql.cj.exceptions.WrongArgumentException` to the code, the checkstyle will throw the following error.
```
[ant:checkstyle] [WARN] C:\Users\Kache\source\repos\bq-wrapper\wrapper\src\main\java\software\amazon\jdbc\hostlistprovider\AuroraHostListProvider.java:19:1: Illegal import - com.mysql.cj.exceptions.WrongArgumentException. [IllegalImport]
Execution failed for task ':aws-advanced-jdbc-wrapper:checkstyleMain'.
> A failure occurred while executing org.gradle.api.plugins.quality.internal.CheckstyleAction
> Checkstyle rule violations were found. See the report at: file:///C:/Users/Kache/source/repos/bq-wrapper/wrapper/build/reports/checkstyle/main.html
Checkstyle files with violations: 1
Checkstyle violations by …
```
=> chore: add driver-specific imports to the checkstyle warning list

wrapper/src/main/java/software/amazon/jdbc/exceptions/PgExceptionHandler.java
Add 28000 to the access exception codes list.
=> fix: add 28000 to login exception list

wrapper/src/main/java/software/amazon/jdbc/plugin/IamAuthConnectionPlugin.java, wrapper/src/main/resources/messages.properties
Add connect exception handling to IAM plugin
@karenc-bq 
@aaron-congo 
@hsuamz 
=> add connect exception handling to IAM plugin

wrapper/src/test/java/software/amazon/logging/ExtendedFormatter.java, wrapper/src/test/resources/logging-test.properties
Extend test logs with thread name
@karenc-bq 
@aaron-congo 
=> Extend logs with thread name

config/checkstyle/checkstyle-suppressions.xml, wrapper/src/main/java/software/amazon/jdbc/DriverConnectionProvider.java
Fix:
- checkstyle failure due to modified license
- driver connection provider passing original properties resulting properties being overridden for subsequent connections.
Changes derived from PR #468
=> fix: checkstyle and properties being overridden

wrapper/src/main/java/software/amazon/jdbc/plugin/AuroraConnectionTrackerPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/OpenedConnectionTracker.java
Prune null connections in the connection tracker
Some connections, after resources being released, remain in the connection tracker even though they are null. The existing methods that remove connections from queues do not check all the queues in the tracker and do not consider null connections, which allows them to linger. This PR adds a method to remove null connections from the tracker.
=> fix: prune null connections in the connection tracker

wrapper/src/test/resources/logging-test.properties
Update logging format so it is easier to distinguish the logger name from the log message.
**Before**:
`[2023-05-27 01:45:06.090] [FINEST ] [HikariPool-1 connection adder] software.amazon.jdbc.util.PropertyUtils setPropertyOnTarget Set method for property 'database' does not exist on target 'class com.mysql.cj.jdbc.MysqlDataSource'. `
**After**:
`[2023-05-27 01:45:06.090] [FINEST ] [HikariPool-1 connection adder] [software.amazon.jdbc.util.PropertyUtils setPropertyOnTarget] : Set method for property 'database' does not exist on target 'class com.mysql.cj.jdbc.MysqlDataSource'. `
=> chore: update logging format

wrapper/src/main/java/software/amazon/jdbc/plugin/IamAuthConnectionPlugin.java, wrapper/src/main/resources/messages.properties, wrapper/src/test/java/software/amazon/jdbc/plugin/IamAuthConnectionPluginTest.java
Fix in the IamAuthConnectionPlugin to prioritize the override property IAM_DEFAULT_PORT then Hosts port, and then Dialect port. 
Fix in the IamAuthConnectionPlugin to prioritize the override property IAM_DEFAULT_PORT then Hosts port, and then Dialect port. 
This also results in change of behaviour. When an invalid port value is specified for IAM_DEFAULT_PORT, it no longer throws an exception, but rather logs a warning and then falls back on either the Host port or Dialect default port. 
@sergiyv-improving @karenc-bq @aaron-congo @crystall-bitquill
=> fix: IAM_DEFAULT_PORT property to override host and dialect ports.

CHANGELOG.md, wrapper/src/main/java/software/amazon/jdbc/Driver.java
Let wrapperLoggerLevel values be case insensitive
The driver currently only accepts capitalized values for the `wrapperLoggerLevel` parameter. This PR will accept any capitalization.
=> fix: Let wrapperLoggerLevel values be case insensitive

CHANGELOG.md, benchmarks/README.md, docs/GettingStarted.md, docs/using-the-jdbc-driver/UsingTheJdbcDriver.md, gradle.properties, wrapper/src/test/resources/hibernate_files/hibernate-core.gradle, wrapper/src/test/resources/hibernate_files/java-module.gradle
Update changelog and versioning for 2.2.0
=> chore: update changelog and versioning for 2.2.0

CHANGELOG.md, examples/SpringBootHikariExample/README.md, examples/SpringBootHikariExample/build.gradle.kts, examples/SpringBootHikariExample/gradle.properties, examples/SpringBootHikariExample/src/main/java/software/amazon/SpringBootHikariExample/ApiController.java, examples/SpringBootHikariExample/src/main/java/software/amazon/SpringBootHikariExample/SpringBootHikariExampleApplication.java, examples/SpringBootHikariExample/src/main/resources/application.yml, examples/SpringHibernateExample/README.md, examples/SpringWildflyExample/README.md, settings.gradle.kts
Add tutorial and code samples with Spring and Hikari
Add tutorial and code samples with Spring and Hikari
@karenc-bq @sergiyv-improving @aaron-congo @crystall-bitquill
=> doc: Add tutorial and code samples with Spring and Hikari

wrapper/src/test/java/integration/refactored/TestEnvironmentRequest.java, wrapper/src/test/java/integration/refactored/container/TestDriverProvider.java, wrapper/src/test/java/integration/refactored/container/tests/AuroraFailoverTest.java, wrapper/src/test/java/integration/refactored/host/TestEnvironment.java, wrapper/src/test/java/integration/refactored/host/TestEnvironmentProvider.java, wrapper/src/test/java/integration/util/AuroraTestUtility.java
Improve integration suite performance by creating required test DB clusters in advance.
=> Improve integration suite performance

docs/using-the-jdbc-driver/Frameworks.md, docs/using-the-jdbc-driver/using-plugins/UsingTheAwsSecretsManagerPlugin.md, docs/using-the-jdbc-driver/using-plugins/UsingTheIamAuthenticationPlugin.md
=> docs: update links in documentation

wrapper/src/main/java/software/amazon/jdbc/Driver.java, wrapper/src/main/resources/messages.properties
Update the error message so the stacktrace provides more information when DriverManger throws an exception regarding no suitable drivers.
New message:
```
Exception in thread "main" java.sql.SQLException: Can't find the target driver for 'jdbc:postgresql://database-pg.cluster-xyz.us-east-2.rds.amazonaws.com/postgres'. Please ensure the target driver is on the classpath. Here is the list of registered drivers on the classpath: [[software.amazon.jdbc.Driver@736e9adb, com.mysql.cj.jdbc.Driver@deb6432]]
at software.amazon.jdbc.Driver.connect(Driver.java:108)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
at software.amazon.PGSimple.main(PGSimple.java:40)
Caused by: java.sql.SQLException: No …
```
=> chore: update error message for when target drivers are not found

examples/AWSDriverExample/build.gradle.kts, wrapper/build.gradle.kts, wrapper/src/test/build.gradle.kts
Upgrade org.springframework.boot:spring-boot-starter-jdbc from 2.7.+ to 3.1.1
@karenc-bq
=> Upgrade org.springframework.boot:spring-boot-starter-jdbc from 2.7.+ to 3.1.1

README.md, docs/GettingStarted.md, docs/using-the-jdbc-driver/using-plugins/UsingTheAwsSecretsManagerPlugin.md, examples/AWSDriverExample/src/main/java/software/amazon/AwsSecretsManagerConnectionPluginPostgresqlExample.java, wrapper/src/main/java/software/amazon/jdbc/plugin/AwsSecretsManagerConnectionPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/efm/MonitorServiceImpl.java, wrapper/src/test/java/integration/container/tests/AdvancedPerformanceTest.java, wrapper/src/test/java/integration/container/tests/HikariTests.java, wrapper/src/test/java/integration/container/tests/PerformanceTest.java, wrapper/src/test/java/software/amazon/jdbc/plugin/AwsSecretsManagerConnectionPluginTest.java, wrapper/src/test/java/software/amazon/jdbc/plugin/efm/ConcurrencyTests.java
This makes it easier to find where configuration parameters are used
=> Put configuration parameters on first page with links to where they are used

.editorconfig, wrapper/build.gradle.kts, wrapper/src/test/java/integration/host/TestEnvironment.java, wrapper/src/test/java/integration/util/ContainerHelper.java
ToxiproxyContainer used to handle the creation of the Toxiproxy client and the proxies. This was recently [deprecated](https://github.com/testcontainers/testcontainers-java/pull/6065) and user applications are encouraged to create their own client.
This PR updates the container helper to create and handle the toxiproxy client for each proxy container instead of relying on the `getProxy` method.
=> test: Update container helper to create proxies

wrapper/src/main/java/software/amazon/jdbc/plugin/readwritesplitting/ReadWriteSplittingPlugin.java, wrapper/src/test/java/software/amazon/jdbc/plugin/readwritesplitting/ReadWriteSplittingPluginTest.java
Propagate `Connection.clearWarnings()` to writer and reader connection
`ReadWriteSplittingPlugin` does not propagate `Connection.clearWarnings()` calls to the underlying reader connection, hence the connection object may accumulate warning messages, and in effect cause a memory leak in the application.
This PR fixes the memory leak problem described in https://github.com/awslabs/aws-advanced-jdbc-wrapper/issues/547
=> Propagate Connection.clearWarnings() to writer and reader connection

wrapper/src/main/java/software/amazon/jdbc/ConnectionPluginChainBuilder.java, wrapper/src/main/java/software/amazon/jdbc/ConnectionPluginManager.java, wrapper/src/main/java/software/amazon/jdbc/PropertyDefinition.java, wrapper/src/test/java/software/amazon/jdbc/ConnectionPluginChainBuilderTests.java
Sort plugins by default to prevent plugin misconfiguration. Allows a user to provide a custom plugin order if needed.
Plugin chain initialization has been separated to `ConnectionPluginChainBuilder `class. Depending on user settings, a plugin factory list is sorted based on plugin assigned weights. 
@karenc-bq @aaron-congo @aaronchung-bitquill @crystall-bitquill
=> sort plugins by default

CHANGELOG.md, wrapper/src/main/java/software/amazon/jdbc/PluginService.java, wrapper/src/main/java/software/amazon/jdbc/PluginServiceImpl.java, wrapper/src/main/java/software/amazon/jdbc/plugin/readwritesplitting/ReadWriteSplittingPlugin.java, wrapper/src/test/java/software/amazon/jdbc/plugin/efm/ConcurrencyTests.java, wrapper/src/test/java/software/amazon/jdbc/plugin/readwritesplitting/ReadWriteSplittingPluginTest.java
Close underlying connections after setReadOnly when using internal connection pooling
From a discussion in PR #548, related to issue #547.
It was determined the underlying reader or writer connections in the Read Write Splitting Plugin should be returned to their connection pools if internal connection pooling is used. This PR will detect if internal connection pooling is used with flags and close connections when appropriate.
=> fix: close underlying connections after setReadOnly when using internal connection pooling

wrapper/src/main/java/software/amazon/jdbc/dialect/AuroraPgDialect.java, wrapper/src/test/java/integration/container/tests/AuroraConnectivityTests.java, wrapper/src/test/java/integration/container/tests/ReadWriteSplittingTests.java, wrapper/src/test/java/integration/util/AuroraTestUtility.java
Update aurora pg topology query to also return instances with null last_update_timestamp
In Aurora PostgreSQL versions 13.9 and above, the instance a user is currently connected to will not include a `last_update_timestamp` when retrieved from `aurora_replica_status()`.  This PR adjusts the topology query to account for the change. 
For example, querying the `last_update_timestamp` for all instance from `aurora_replica_status()` while connecting through the reader cluster url will result in this:
```
server_id          | case |  last_update_timestamp  
-----------------------------+------+------------------------
database-instance-1         | t    | 2023-08-15 00:29:11+00
database-instance-2         | f    | 
```
This PR also bumps the integration test engine version to 13.9
Addresses …
=> fix: update aurora pg topology query to also return instances with null last_update_timestamp

wrapper/src/main/java/software/amazon/jdbc/plugin/efm/MonitorImpl.java
The original condition is to prevent passing a negative value to `sleep`. However min check time is 3 seconds. Setting the delays to 3 seconds when the delay is nonnegative has negative performance impacts.
=> fix: condition setting delayMillis

README.md
Fix Maven coordinates in README
As per the link above the text blob in `README.md`, https://search.maven.org/search?q=g:software.amazon.jdbc, the group ID is `software.amazon.jdbc`.
=> Fix Maven coordinates in README

README.md, docs/Documentation.md, docs/KnownLimitations.md, examples/VertxExample/src/main/java/com/example/starter/MainVerticle.java
Minor documentation updates
- Moved the known limitations to the main read me
- Changed the wording on the blue/green deployments limitation
- Change a url from reader cluster to cluster in VertX example
Related to #678
=> docs: add known limitations to main readme and fix example url

wrapper/src/main/java/software/amazon/jdbc/plugin/failover/FailoverConnectionPlugin.java, wrapper/src/main/java/software/amazon/jdbc/util/SubscribedMethodHelper.java
Update topology for specific methods
Specify a list of methods where it's safe to update the topology before executing to prevent error where connection objects have more than one streaming result set open at the same time.
=> fix: update topology for specific methods

wrapper/src/main/java/software/amazon/jdbc/DataSourceConnectionProvider.java, wrapper/src/main/java/software/amazon/jdbc/DriverConnectionProvider.java, wrapper/src/main/java/software/amazon/jdbc/HikariPooledConnectionProvider.java, wrapper/src/main/java/software/amazon/jdbc/dialect/Dialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/MariaDbDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/MysqlDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/PgDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/UnknownDialect.java
Allow dialect classes to modify properties while opening a new connection.
Dialect interface is extended with prepareConnectProperties(). It's called by connection provider before target driver dialect gets a chance to do similar preparation.
@karenc-bq 
@brunos-bq 
@hsuamz
=> introduce Dialect.prepareConnectProperties

wrapper/src/main/java/software/amazon/jdbc/plugin/efm/MonitorImpl.java, wrapper/src/main/resources/aws_advanced_jdbc_wrapper_messages.properties
Add additional logging for efm
- Adds additional logging in the `MonitorImpl` class for previously unhandled exceptions and for scenarios where monitoring has stopped but the `startMonitoring` method was called again.
- Changes the monitoring loop to continue running unless an InterruptedException is thrown.
Related to #675
=> fix: continue monitoring if unhandled Exception is thrown

docs/using-the-jdbc-driver/UsingTheJdbcDriver.md, wrapper/src/main/java/software/amazon/jdbc/ConnectionProviderManager.java, wrapper/src/main/java/software/amazon/jdbc/plugin/DefaultConnectionPlugin.java, wrapper/src/test/java/software/amazon/jdbc/plugin/DefaultConnectionPluginTest.java
Allow user to set up a lambda to initialize new connections.
User needs to set an connection initialization function with ConnectionProviderManager.setConnectionInitFunc()
Related to https://github.com/awslabs/aws-advanced-jdbc-wrapper/issues/679
@karenc-bq 
@brunos-bq 
=> Allow user to set up a lambda to initialize new connections

docs/using-the-jdbc-driver/using-plugins/UsingTheAwsSecretsManagerPlugin.md, wrapper/src/main/java/software/amazon/jdbc/plugin/AwsSecretsManagerConnectionPlugin.java, wrapper/src/main/resources/aws_advanced_jdbc_wrapper_messages.properties
Allow endpoint override for secrets manager plugin
- adds the configuration parameter `secretsManagerEndpoint` to allow users to set the endpoint override for secret retrieval in the secrets manager plugin
Addresses #630
=> feat: allow endpoint override for secrets manager plugin

wrapper/src/main/java/software/amazon/jdbc/DriverConnectionProvider.java, wrapper/src/main/java/software/amazon/jdbc/targetdriverdialect/GenericTargetDriverDialect.java, wrapper/src/main/java/software/amazon/jdbc/util/PropertyUtils.java
fix: using masked properties for logging
@sergiyv-improving
=> fix: using masked properties for logging

wrapper/src/main/java/software/amazon/jdbc/PluginService.java, wrapper/src/main/java/software/amazon/jdbc/PluginServiceImpl.java, wrapper/src/main/java/software/amazon/jdbc/plugin/failover/FailoverConnectionPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/readwritesplitting/ReadWriteSplittingPlugin.java, wrapper/src/main/java/software/amazon/jdbc/states/RestoreSessionStateCallable.java, wrapper/src/main/java/software/amazon/jdbc/states/SessionDirtyFlag.java, wrapper/src/main/java/software/amazon/jdbc/states/SessionStateHelper.java, wrapper/src/main/java/software/amazon/jdbc/states/SessionStateTransferCallable.java, wrapper/src/main/java/software/amazon/jdbc/wrapper/ConnectionWrapper.java, wrapper/src/test/java/software/amazon/jdbc/plugin/efm/ConcurrencyTests.java, wrapper/src/test/java/software/amazon/jdbc/plugin/failover/FailoverConnectionPluginTest.java, wrapper/src/test/java/software/amazon/jdbc/plugin/readwritesplitting/ReadWriteSplittingPluginTest.java
- track session states
- allow user to provide custom function to handle session state transfers
@karenc-bq 
@davecramer 
@hsuamz
=> Track session states

wrapper/src/test/java/integration/container/TestDriverProvider.java, wrapper/src/test/java/integration/container/tests/ReadWriteSplittingTests.java
Disable failing integration test for PG driver
@karenc-bq 
@aaron-congo 
@brunos-bq
=> Disable failing integration test for PG driver

wrapper/src/main/java/software/amazon/jdbc/ConnectionPluginChainBuilder.java, wrapper/src/main/java/software/amazon/jdbc/ConnectionPluginManager.java, wrapper/src/main/java/software/amazon/jdbc/hostlistprovider/RdsHostListProvider.java, wrapper/src/main/java/software/amazon/jdbc/plugin/AbstractConnectionPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/efm/HostMonitoringConnectionPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/strategy/fastestresponse/FastestResponseStrategyPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/strategy/fastestresponse/FastestResponseStrategyPluginFactory.java, wrapper/src/main/java/software/amazon/jdbc/plugin/strategy/fastestresponse/HostResponseTimeService.java, wrapper/src/main/java/software/amazon/jdbc/plugin/strategy/fastestresponse/HostResponseTimeServiceImpl.java, wrapper/src/main/java/software/amazon/jdbc/plugin/strategy/fastestresponse/NodeResponseTimeMonitor.java, wrapper/src/main/java/software/amazon/jdbc/profile/DriverConfigurationProfiles.java, wrapper/src/main/java/software/amazon/jdbc/targetdriverdialect/GenericTargetDriverDialect.java, wrapper/src/main/java/software/amazon/jdbc/targetdriverdialect/MysqlConnectorJTargetDriverDialect.java, wrapper/src/main/java/software/amazon/jdbc/targetdriverdialect/TargetDriverDialect.java, wrapper/src/main/java/software/amazon/jdbc/util/CacheMap.java, wrapper/src/main/java/software/amazon/jdbc/util/SlidingExpirationCache.java, wrapper/src/main/java/software/amazon/jdbc/util/SlidingExpirationCacheWithCleanupThread.java, wrapper/src/main/resources/aws_advanced_jdbc_wrapper_messages.properties
Implement a new fastest response time strategy.
- Strategy is implemented as `FastestResponseStrategyPlugin`
- Node response time (milliseconds) is measured in a separate thread and is implemented in `NodeResponseTimeMonitor`. Configuration parameters for a database connection in that thread could be provided with a prefix `frt-` (similar to Host Monitoring Plugin).
- Node monitoring (measuring of response time) uses a sliding expiration approach. If it's not been called for a response time for 10 min, monitoring thread stops. When topology changes, new nodes will be added to monitoring.
- Thread reports current node response time to telemetry engine. Number of currently monitored nodes is reported as well.
@karenc-bq 
@aaron-congo 
@brunos-bq 
@crystall-bitquill
=> feat: node fastest response time strategy

wrapper/src/main/java/software/amazon/jdbc/RoundRobinHostSelector.java
Use existing entries to update the round robin cache
The round robin cache is updated if all hosts have a cache entry, and if there are no existing cache entries for any host, new entries will be made for all hosts. This is missing the case where only some hosts have cache entries available. This PR amends the update cache conditions to include this scenario.
=> fix: use existing entries to update the round robin cache

docs/using-the-jdbc-driver/DataSource.md, examples/HikariExample/src/main/java/software/amazon/HikariExample.java, examples/HikariExample/src/main/java/software/amazon/HikariFailoverExample.java
Update HikariCP example to include configuring the datasource with a JDBC URL
The existing example only uses the individual data source properties. This PR includes the option of using a URL in the example and clarifies that it is possible to use URLs.
=> docs: update HikariCP example to include configuring the datasource with a JDBC URL

wrapper/src/main/java/software/amazon/jdbc/util/SqlMethodAnalyzer.java, wrapper/src/test/java/software/amazon/jdbc/util/SqlMethodAnalyzerTest.java
=> fix: SqlMethodAnalyzer to handle empty SQL query and not throw IndexOutOfBoundsException

examples/ReadWriteSplittingSample/build.gradle.kts, examples/ReadWriteSplittingSample/gradle.properties, examples/ReadWriteSplittingSample/src/main/java/software/amazon/ReadWriteSplittingSample.java, examples/ReadWriteSplittingSample/src/main/resources/logging.properties, settings.gradle.kts
=> Add example code for Read/Write Splitting sample

wrapper/src/main/java/software/amazon/jdbc/dialect/AuroraMysqlDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/AuroraPgDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/MariaDbDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/MysqlDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/PgDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/RdsMultiAzDbClusterMysqlDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/RdsMultiAzDbClusterPgDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/RdsMysqlDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/RdsPgDialect.java
[](fix: handling exceptions when multi AZ isDialect() function fails)
@sergiyv-improving
=> fix: restructuring try blocks in dialects for exception handling

wrapper/src/main/java/software/amazon/jdbc/Driver.java, wrapper/src/main/java/software/amazon/jdbc/DriverConnectionProvider.java, wrapper/src/main/java/software/amazon/jdbc/plugin/failover/FailoverConnectionPlugin.java
Address the issue with session state transfer during failover. 
https://github.com/awslabs/aws-advanced-jdbc-wrapper/issues/812
@karenc-bq 
@brunos-bq
=> transfer session state during failover

wrapper/src/main/java/software/amazon/jdbc/dialect/DialectManager.java, wrapper/src/main/java/software/amazon/jdbc/dialect/RdsMultiAzDbClusterMysqlDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/RdsMultiAzDbClusterPgDialect.java
Improve Multi-AZ cluster detection. Increase host-to-dialect cache expiration time.
Related to https://github.com/awslabs/aws-advanced-jdbc-wrapper/discussions/796
@karenc-bq 
@brunos-bq 
=> Improve Multi-AZ cluster detection

wrapper/src/main/java/software/amazon/jdbc/plugin/efm/MonitorImpl.java, wrapper/src/test/java/software/amazon/jdbc/plugin/efm/MonitorImplTest.java
Release all stopped monitors
In the `MonitorImpl` class, a stopped monitor is not always removed from the monitor thread container monitor map. This means it may potentially be chosen again when a monitor is retrieved. This PR makes the monitor thread container release the resources attached to individual monitors once the monitor has been stopped.
=> fix: release all stopped monitors

wrapper/src/main/java/software/amazon/jdbc/dialect/MariaDbDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/RdsMysqlDialect.java, wrapper/src/test/java/integration/util/ContainerHelper.java, wrapper/src/test/java/software/amazon/jdbc/DialectDetectionTests.java
Add update candidates for the MariaDB dialect and fix the RDS MySQL dialect incorrectly returning false in the isDialect method
- Added update candidates for the MariaDB dialect in order to swap to MySQL dialects in the case of using a MySQL database with the protocol `jdbc:aws-wrapper:mariadb://`.
- Fixed the isDialect method of the RDS MySQL dialect. The method would return false if the MySQL dialect `isDialect` method also returned false. The MySQL isDialect method depends on whether the `version_comment` variable contains the value `mysql` but the RDS MySQL isDialect methods depends on whether the `version_comment` variable is equal to `Source distribution`.
Related to #789
=> fix: add update candidates for the maria db dialect; fix rds mysql dialect incorrectly returning false in isDialect method

wrapper/build.gradle.kts
chore: re-add java.sql.Driver service to wrapper jar task
chore: re-add java.sql.Driver service to wrapper jar task
This is to address that gradle `build` task did not include the java.sql.Driver service, despite the publish task doing so.
=> chore: re-add java.sql.Driver service to wrapper jar task

wrapper/src/main/java/software/amazon/jdbc/LeastConnectionsHostSelector.java, wrapper/src/main/java/software/amazon/jdbc/RandomHostSelector.java, wrapper/src/main/java/software/amazon/jdbc/RoundRobinHostSelector.java, wrapper/src/test/java/RandomHostSelectorTests.java
feat: update HostSelector implementations to account for HostAvailablity
For each implementation of HostSelector, it filters and creates a list of eligible hosts. Added an extra condition to only filter out ones that are `HostAvailability.NOT_AVAILABLE`
=> feat: update HostSelector implementations to account for HostAvailablity

wrapper/src/main/java/software/amazon/jdbc/util/RdsUtils.java, wrapper/src/test/java/integration/container/TestDriverProvider.java, wrapper/src/test/java/software/amazon/jdbc/util/RdsUtilsTests.java
Reduce number of calls to Matcher.find to improve performance.
Baseline performance:
Identifying the cluster type takes longer than executing statements.
After the refactoring:
=> refactor: reduce regex checks to improve performance

wrapper/src/main/java/software/amazon/jdbc/ConnectionPluginManager.java, wrapper/src/main/java/software/amazon/jdbc/util/AsynchronousMethodsHelper.java, wrapper/src/main/java/software/amazon/jdbc/util/WrapperUtils.java, wrapper/src/main/resources/aws_advanced_jdbc_wrapper_messages.properties, wrapper/src/test/java/software/amazon/jdbc/util/WrapperUtilsTest.java
Statement cancel not working with MySQL driver
The Statement.cancel method currently does not function with the MySQL community driver due to locking the ConnectionPluginManager. The MySQL driver also synchronizes on the Statement.getConnection method, which blocks any Statement.cancel executions. This PR moves the lock location and skips executing Statement.getConnection when running Statement.cancel.
=> fix: statement cancel not working with mysql driver

wrapper/src/main/java/software/amazon/jdbc/HostSpecBuilder.java, wrapper/src/main/java/software/amazon/jdbc/hostlistprovider/RdsHostListProvider.java, wrapper/src/test/java/software/amazon/jdbc/hostlistprovider/RdsHostListProviderTest.java
feat: HostSpec to not default lastUpdateTime. Handle null lastUpdateTime in RdsHostListProvider
No more defaultLastUpdateTime in the HostSpecBuilder (previously it would default if lastUpdateTime was `null`).
In the `RdsHostListProvider#processQueryResults` where it sorts writer hosts based on `lastUpdateTime`, it handles null `lastUpdateTime` values by sorting/deprioritizing them to last.
=> feat: HostSpec to not default lastUpdateTime. Handle null lastUpdateTime in RdsHostListProvider

wrapper/src/main/java/software/amazon/jdbc/plugin/failover/FailoverConnectionPlugin.java, wrapper/src/main/java/software/amazon/jdbc/targetdriverdialect/GenericTargetDriverDialect.java, wrapper/src/main/java/software/amazon/jdbc/targetdriverdialect/MariadbTargetDriverDialect.java, wrapper/src/main/java/software/amazon/jdbc/targetdriverdialect/MysqlConnectorJTargetDriverDialect.java, wrapper/src/main/java/software/amazon/jdbc/targetdriverdialect/PgTargetDriverDialect.java, wrapper/src/main/java/software/amazon/jdbc/targetdriverdialect/TargetDriverDialect.java
Add check for target dialect specific method calls allowed on closed connections
Used Hashset to store allowed methods. Change to check dialect specific methods instead of generic ones
=> chore: target driver dialect in closed connections

.github/workflows/run-hibernate-orm-tests.yml, .github/workflows/run-standard-integration-tests.yml
…even if failing
fix: hibernate-orm and standard-integration tests to publish results even if failing.
Fixes issue https://github.com/orgs/awslabs/projects/91/views/13?pane=issue&itemId=52456842
For those tests, added `!canceled()` to the status check expression of the publishing steps so that even if the previous steps fail, it will still publish results. 
NOTE: also included a change to an integration test that is expected to fail for testing.
=> fix: hibernate-orm and standard-integration tests to publish results even if failing

benchmarks/build.gradle.kts, examples/AWSDriverExample/build.gradle.kts, examples/HikariExample/build.gradle.kts, examples/ReadWriteSplittingSample/build.gradle.kts, examples/SpringBootHikariExample/build.gradle.kts, examples/SpringHibernateBalancedReaderOneDataSourceExample/build.gradle.kts, examples/SpringHibernateBalancedReaderTwoDataSourceExample/build.gradle.kts, examples/SpringHibernateExample/build.gradle.kts, examples/SpringWildflyExample/spring/build.gradle.kts, examples/VertxExample/build.gradle.kts, wrapper/build.gradle.kts
Update PGJDBC version to 42.7.2. The updated dependency addresses a [CVE-2024-1597](https://www.cve.org/CVERecord?id=CVE-2024-1597) and [Security Advisory](https://github.com/pgjdbc/pgjdbc/security/advisories/GHSA-24rp-q3w6-vc56) found in the PGJDBC driver. The vulnerability occurs only in non-default `preferQueryMode=simple` mode and only if a negative place holder `-? `is used. See the security advisory for details
=> chore: update PGJDBC version to 42.7.2

CHANGELOG.md, aws-advanced-jdbc-wrapper-bundle/build.gradle.kts, examples/AWSDriverExample/build.gradle.kts, examples/SpringHibernateBalancedReaderOneDataSourceExample/build.gradle.kts, examples/SpringHibernateBalancedReaderTwoDataSourceExample/build.gradle.kts, examples/SpringHibernateExample/build.gradle.kts, examples/SpringTxFailoverExample/README.md, examples/SpringWildflyExample/spring/build.gradle.kts, wrapper/build.gradle.kts, wrapper/src/main/java/software/amazon/jdbc/ConnectionPluginManager.java, wrapper/src/main/java/software/amazon/jdbc/util/WrapperUtils.java, wrapper/src/test/build.gradle.kts, wrapper/src/test/java/integration/container/tests/AuroraFailoverTest.java, wrapper/src/test/java/software/amazon/jdbc/ConnectionPluginManagerTests.java, wrapper/src/test/java/software/amazon/jdbc/util/WrapperUtilsTest.java
Fix the issue with multithreading lock
https://github.com/awslabs/aws-advanced-jdbc-wrapper/issues/917
@karenc-bq 
=> fix: issue with multithreading lock

wrapper/src/main/java/software/amazon/jdbc/hostlistprovider/ConnectionStringHostListProvider.java, wrapper/src/main/resources/aws_advanced_jdbc_wrapper_messages.properties
chore: ConnectionStringHostListProvider to not support identifyConnection() since it is not used
remove code from ConnectionStringHostListProvider.identifyConnection() and throw UnsupportedOperationException() since it is not used.
=> chore: ConnectionStringHostListProvider to not support identifyConnection() since it is not used

wrapper/src/main/java/software/amazon/jdbc/HostSpec.java, wrapper/src/main/java/software/amazon/jdbc/hostlistprovider/RdsHostListProvider.java, wrapper/src/main/java/software/amazon/jdbc/util/RdsUtils.java, wrapper/src/test/java/integration/host/TestEnvironment.java, wrapper/src/test/java/software/amazon/jdbc/hostlistprovider/RdsHostListProviderTest.java, wrapper/src/test/java/software/amazon/jdbc/hostlistprovider/RdsMultiAzDbClusterListProviderTest.java
fix: connection identification and tracking
@karenc-bq 
=> fix: connection identification and tracking

docs/using-the-jdbc-driver/using-plugins/UsingTheOktaAuthPlugin.md
Remove `[!warning]` from the Okta documentation to stay consistent with the other authentication documentation
=> docs: remove warning sign

.github/workflows/run-autoscaling-tests.yml, .github/workflows/run-hibernate-orm-tests.yml, .github/workflows/run-integration-tests-latest.yml, .github/workflows/run-integration-tests-lts.yml, .github/workflows/run-standard-integration-tests.yml, wrapper/build.gradle.kts
Mask sensitive data in html unit test reports
@karenc-bq 
@hsuamz
=> chore: mask sensitive data in html unit test reports

wrapper/src/main/java/software/amazon/jdbc/util/ConnectionUrlParser.java, wrapper/src/test/java/software/amazon/jdbc/util/ConnectionUrlParserTest.java
The driver was incorrectly truncating nested connection options when parsing connection urls.
Connecting with a string similar to `?options=-c%20search_path=test,public,pg_catalog%20-c%20statement_timeout=90000` would result in unexpected errors:
```
Exception in thread "main" org.postgresql.util.PSQLException: FATAL: -c search_path requires a value
```
This PR updates the parsing logic to properly handle nested options.
=> fix: parse nested options

wrapper/src/main/java/software/amazon/jdbc/util/RdsUtils.java, wrapper/src/test/java/software/amazon/jdbc/util/RdsUtilsTests.java
Addresses Issue 998, RdsUtils.java does not support regions such as us-isob-east-1 which do not have amazonaws.com suffixes in endpoint names.
Modified Patterns AURORA_DNS_PATTERN and AURORA_CLUSTER_PATTERN to include domains sc2s.sgov.gov and c2s.ic.gov and added test cases to RdsUtilsTests.java
=> changes to RDSUtils.java, extend Pattern coverage

wrapper/src/main/java/software/amazon/jdbc/HostSpec.java, wrapper/src/main/java/software/amazon/jdbc/hostlistprovider/RdsHostListProvider.java, wrapper/src/main/java/software/amazon/jdbc/util/RdsUtils.java, wrapper/src/test/java/software/amazon/jdbc/hostlistprovider/RdsHostListProviderTest.java, wrapper/src/test/java/software/amazon/jdbc/hostlistprovider/RdsMultiAzDbClusterListProviderTest.java, wrapper/src/test/java/software/amazon/jdbc/util/RdsUtilsTests.java
fix governmental endpoints
The following GovCloud DNS patterns should be supported:
rds.<region>.c2s.ic.gov
rds.<region>.amazonaws.com
@karenc-bq
@jasonli-improving
=> fix: GovCloud DNS patterns

wrapper/src/main/java/software/amazon/jdbc/DataSourceConnectionProvider.java
- store enableGreenNodeReplacement parameter value so it can be correctly accessed after removing wrapper specific properties before connecting
- fixes #1059 
Before establishing connections using the DataSource, the wrapper removes all wrapper-specific connection properties to avoid errors. This can be problematic when the connection fails and the wrapper needs to access wrapper-specific properties to perform specific handling. This fix moves the removal logic to the lowest-level method possible to address this issue.
=> fix: enableGreenNodeReplacement being ignored 

wrapper/src/main/java/software/amazon/jdbc/util/WrapperUtils.java, wrapper/src/test/java/software/amazon/jdbc/util/WrapperUtilsTest.java
Fix #1045 (Incompatibility with Hibernate 6.5)
@karenc-bq 
=> fix issue with Statement object cast

aws-advanced-jdbc-wrapper-bundle/build.gradle.kts
The bundled jar for ADFS authentication was missing a required dependency, causing a NullPointerException when using the jar.
=> fix: using bundled jar with adfs throws nullpointerexception

wrapper/src/main/java/software/amazon/jdbc/exceptions/AbstractPgExceptionHandler.java, wrapper/src/main/java/software/amazon/jdbc/exceptions/GenericExceptionHandler.java, wrapper/src/main/java/software/amazon/jdbc/exceptions/MySQLExceptionHandler.java
fix: unwrap nested exceptions when checking for login exceptions
- fixes #1081 
- when the secrets manager secret is rotated, the MySQL driver throws a nested exception where the outer exception does not indicate a login exception but the inner exception does. Prior to these changes, our driver incorrectly concluded that this was not a login exception and threw the exception. With these changes, our driver recognizes it as a login exception and re-fetches the rotated secret, allowing the connection to be retrieved. 
- note that this fix was made in the old aws mysql driver repo but has not been ported over yet (see [here](https://github.com/awslabs/aws-mysql-jdbc/pull/275))
=> fix: unwrap nested exceptions when checking for login exceptions

wrapper/src/main/java/software/amazon/jdbc/RoundRobinHostSelector.java, wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterMonitor.java, wrapper/src/test/java/software/amazon/jdbc/RoundRobinHostSelectorTest.java
Use hostId instead of host to retrieve the host weight pairs
The round robin host selector strategy was using the host instance of the hostId to obtain user provided weights from the `roundRobinHostWeightPairs` property.
=> fix: use hostId instead of host to retrieve the host weight pairs

CHANGELOG.md, wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterMonitor.java
The column name for the router query is changing names. This is to adjust to that.
=> feat: Limitless plugin - change column name from dns_host to router_endpoint in router query

wrapper/src/main/java/software/amazon/jdbc/PluginService.java, wrapper/src/main/java/software/amazon/jdbc/PluginServiceImpl.java, wrapper/src/main/java/software/amazon/jdbc/dialect/AuroraMysqlDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/AuroraPgDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/RdsMultiAzDbClusterMysqlDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/RdsMultiAzDbClusterPgDialect.java, wrapper/src/test/java/software/amazon/jdbc/DialectDetectionTests.java, wrapper/src/test/java/software/amazon/jdbc/plugin/efm/ConcurrencyTests.java
Verify plugin presence based on actual plugin list
https://github.com/aws/aws-advanced-jdbc-wrapper/issues/1140
@karenc-bq 
@aaron-congo 
=> Verify plugin presence based on actual plugin list

wrapper/src/main/java/software/amazon/jdbc/plugin/failover2/FailoverConnectionPlugin.java
Allows failover2 plugin to perform a failover during opening a new connection.
@karenc-bq 
@aaron-congo
=> failover2 on connect

wrapper/src/main/java/software/amazon/jdbc/util/WrapperUtils.java, wrapper/src/test/java/software/amazon/jdbc/util/WrapperUtilsTest.java
Don't attempt to get a statement from a closed ResultSet in getConnectionFromSqlObject.
It's possible that getConnectionFromSqlObject is called on a ResultSet that is already closed, e.g. in DefaultConnectionPlugin when calling .close on a ResultSet. With some implementations, such as PgResultSet, calling getStatement on a closed ResultSet throws an SQLException. There is a performance overhead associated with creating and catching these exceptions everytime a ResultSet is used, and closed, so it should be avoided.
This is similar to an earlier issue fixed here: https://github.com/aws/aws-advanced-jdbc-wrapper/pull/682
=> Don't get Statement from closed ResultSet

wrapper/src/main/java/software/amazon/jdbc/plugin/failover2/FailoverConnectionPlugin.java
Verify opened connection if failover-on-connect is disabled
@karenc-bq 
@aaron-congo
=> verify opened connection if failover on connect is disabled

CHANGELOG.md, wrapper/src/main/java/software/amazon/jdbc/util/SlidingExpirationCache.java, wrapper/src/main/java/software/amazon/jdbc/util/SlidingExpirationCacheWithCleanupThread.java
fix: SlidingExpirationCache and SlidingExpirationCacheWithCleanupThread
Contains fixes for SlidingExpirationCache and SlidingExpirationCacheWithCleanupThread:
- in SlidingExpirationCache, synchronized shouldCleanup check and subsequent removal from cache. This prevents the scenario where a cache item is grabbed after shouldCleanup() returns true but before its removed from the cache.
- in SlidingExpirationCacheWithCleanupThread, some cleanup thread variables were static, which made it so that only one cache could create a cleanup thread. By removing the static keyword we ensure each cache has its own cleanup thread.
=> fix: SlidingExpirationCache and SlidingExpirationCacheWithCleanupThread

wrapper/src/main/java/software/amazon/jdbc/ConnectionPluginManager.java, wrapper/src/main/java/software/amazon/jdbc/util/RdsUtils.java, wrapper/src/test/java/software/amazon/jdbc/util/RdsUtilsTests.java
fix - update limitless DB Shard Group DNS pattern
Change the limitless DNS Pattern from "limitless" to "dbshardgrp"
=> fix - update limitless DB Shard Group DNS pattern

CHANGELOG.md, docs/using-the-jdbc-driver/using-plugins/UsingTheLimitlessConnectionPlugin.md, wrapper/src/main/java/software/amazon/jdbc/HostSpec.java, wrapper/src/main/java/software/amazon/jdbc/dialect/AuroraLimitlessDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/AuroraPgDialect.java, wrapper/src/main/java/software/amazon/jdbc/dialect/DialectManager.java, wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessConnectionPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessQueryHelper.java, wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterMonitor.java, wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterMonitorInitializer.java, wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterService.java, wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterServiceImpl.java, wrapper/src/main/java/software/amazon/jdbc/util/SlidingExpirationCache.java, wrapper/src/main/resources/aws_advanced_jdbc_wrapper_messages.properties, wrapper/src/test/java/software/amazon/jdbc/plugin/limitless/LimitlessConnectionPluginTest.java, wrapper/src/test/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterServiceImplTest.java, wrapper/src/test/java/software/amazon/jdbc/util/RdsUtilsTests.java
Add checks for limitless dialect  + refactor synchronous router fetch #1148
- added dialect checks in mulitple places. 
- new code path incase dialect is not right, and trying to resolve it
- move limitless router endpoint fetching to a helper class `LimitlessQueryHelper`. 
- move synchronous fetch of limitless routers into service class
- move router cache out of monitor and into service
- add `put` method to SlidingExpirationCache
- added a check in DialectManager specifically for PG Limitless to resolve to Aurora PG dialect
=> Fix/limitless dialect check + refactor synchronous router fetch

wrapper/src/test/java/integration/container/tests/CustomEndpointTest.java
Fixes two problems with the Custom Endpoint Plugin integration tests:
- custom endpoints are not allowed with multi-az deployments, so this commit disables the tests for multi-az
- every custom endpoint ID in a given region has to be unique, even between different clusters. Appending a unique string to the custom endpoint IDs should ensure each cluster created for our integration tests has uniquely named custom endpoints
=> Fix CustomEndpointTest initialization

wrapper/src/main/java/software/amazon/jdbc/plugin/customendpoint/CustomEndpointMonitorImpl.java, wrapper/src/main/java/software/amazon/jdbc/plugin/readwritesplitting/ReadWriteSplittingPlugin.java, wrapper/src/main/java/software/amazon/jdbc/util/RegionUtils.java, wrapper/src/test/java/integration/container/tests/CustomEndpointTest.java
- Math.min was mistakenly used where Math.max should have been used, resulting in the custom endpoint monitor never sleeping. This PR corrects the logic so that the monitor obeys sleeps according to the refresh rate
- also includes some other minor fixes and cleans up the custom endpoint test
=> fix: ensure custom endpoint monitor obeys refresh rate

CHANGELOG.md, wrapper/src/main/java/software/amazon/jdbc/plugin/failover/FailoverConnectionPlugin.java, wrapper/src/main/java/software/amazon/jdbc/util/AsynchronousMethodsHelper.java
- fixes #1173 
- abort was not interrupting queries because the plugin manager was locked during query execution and abort was not included in ASYNCHRONOUS_METHODS. This PR fixes this problem by allowing abort to be executed asynchronously
- after allowing asynchronous abort, the exception triggered by abort was triggering failover. To avoid this, closedExplicitly is set when abort is called and checked in shouldExceptionTriggerConnectionSwitch
=> fix: ensure abort interrupts running queries

README.md
=> docs: Clarify support for global databases

wrapper/src/main/java/software/amazon/jdbc/util/telemetry/NullTelemetryFactory.java
While testing our application for regressions in performance after adopting aws-advanced-jdbc-wrapper we found a lot of useless allocations from the NullTelemetryFactory [1].
[1] ![Screenshot 2024-11-12 131311](https://github.com/user-attachments/assets/d4f95f91-ee70-4161-9c49-5fa44ce76001)
Refactored NullTelemetryFactory to use a singleton instance for NullTelemetryContext, TelemetryCounter, and TelemetryGauge, eliminating repeated object creation and reducing memory allocations. 
I also considered using a caching approach but opted for the singleton pattern to further simplify the code and minimize memory churn. I verified software.amazon.jdbc.util.telemetry.NullTelemetryContext#getName is not used in any code paths.
=> Use singleton for null telemetry objects in NullTelemetryFactory

wrapper/src/main/java/software/amazon/jdbc/util/SubscribedMethodHelper.java
[](https://github.com/aws/aws-advanced-jdbc-wrapper/issues/1168)
@karenc-bq 
@aaron-congo
=> avoid updating topology before setReadOnly()

CHANGELOG.md, wrapper/src/main/java/software/amazon/jdbc/plugin/federatedauth/FederatedAuthPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/federatedauth/OktaAuthPlugin.java, wrapper/src/test/java/software/amazon/jdbc/plugin/federatedauth/FederatedAuthPluginTest.java, wrapper/src/test/java/software/amazon/jdbc/plugin/federatedauth/OktaAuthPluginTest.java
This PR changes the federated authentication and okta authentication plugins to use the user provided iamHost property when generating authentication tokens. Prior to this change, the URL host was being used regardless of what iamHost was set to.
=> fix: use iamHost property in federated auth and okta plugins

wrapper/src/test/java/integration/util/AuroraTestUtility.java
- our test logic executes a DescribeDbEngineVersions request to select the latest Aurora version to run integration tests against. In the past this has selected regular Aurora versions, but recently the latest version returned by the API is a limitless version. This PR fixes the problem by filtering out limitless versions. If we decide we want to test against limitless later, we should add a separate task/workflow.
=> test: exclude limitless versions when selecting latest version for testing

CHANGELOG.md, wrapper/src/main/java/software/amazon/jdbc/hostlistprovider/monitoring/MonitoringRdsHostListProvider.java
- a bug was occurring when using the failover2 plugin with a multi-az cluster URL. The bug was that regular monitors (ClusterTopologyMonitorImpl) were incorrectly being used instead of multi-az monitors (MultiAZClusterTopologyMonitorImpl). This caused regular topology queries to be executed by the monitor instead of multi-az topology queries, leading to the error `Unknown table 'REPLICA_HOST_STATUS' in information_schema`.
- The reason why regular monitors were incorrectly used is that the monitor type depends on the database dialect, and the dialect starts with a default value of Aurora before connecting, and then is updated to a value of multi-az after connecting. The logic to create the monitor was triggered before the dialect was updated, incorrectly resulting in regular monitors. …
=> fix: initialize failover2 topology monitors after dialect is updated

wrapper/src/main/java/software/amazon/jdbc/plugin/customendpoint/CustomEndpointRoleType.java
The AWS Java SDK may return WRITER:
https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/rds/model/CreateDbClusterEndpointResponse.html#customEndpointType()
=> fix: add writer custom endpoint type

wrapper/src/main/java/software/amazon/jdbc/ConnectionPluginManager.java, wrapper/src/main/java/software/amazon/jdbc/ConnectionProviderManager.java, wrapper/src/main/java/software/amazon/jdbc/PluginService.java, wrapper/src/main/java/software/amazon/jdbc/PluginServiceImpl.java, wrapper/src/main/java/software/amazon/jdbc/plugin/DefaultConnectionPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/readwritesplitting/ReadWriteSplittingPlugin.java, wrapper/src/test/java/software/amazon/jdbc/plugin/efm/ConcurrencyTests.java, wrapper/src/test/java/software/amazon/jdbc/plugin/readwritesplitting/ReadWriteSplittingPluginTest.java
chore: verify provider ordering in connection provider manager
- Added effective connection provider to `ConnectionProviderManager`
- Allow `ReadWriteSplittingPlugin` to determine a proper connection provider type.
@karenc-bq 
@aaron-congo 
=> chore: verify provider ordering in connection provider manager

.github/workflows/code_quality.yml, .github/workflows/main.yml, .github/workflows/run-hibernate-orm-tests.yml, .github/workflows/run-standard-integration-tests.yml
chore: change tj-actions/changed-files to directly use SHA reference
=> chore: change tj-actions/changed-files to directly use SHA reference

wrapper/src/main/java/software/amazon/jdbc/util/SlidingExpirationCache.java
Add comment in sliding expiration cache to indicate item has been removed from the cache map.
=> chore: add comment in sliding expiration cache

CHANGELOG.md, wrapper/src/main/java/software/amazon/jdbc/util/ConnectionUrlBuilder.java, wrapper/src/main/resources/aws_advanced_jdbc_wrapper_messages.properties
- fixes #1222 
- before these changes, we encoded the property values passed to the buildUrl function. This function is only actually called when using a MariaDB data source. We do not encode MySQL or Postgres driver/datasource connections, and we do not encode MariaDB driver connections. Encoding the property values for MariaDB changes the intended values for the properties and can cause connection failures (see the linked issue above). I believe this encoding was originally intended to be used with MySQL and/or Postgres, but did not end up being used in those scenarios and isn't required for them either. This PR removes the call to encode the property values.
=> fix: avoid encoding MariaDB connection properties

wrapper/src/main/java/software/amazon/jdbc/Driver.java, wrapper/src/main/java/software/amazon/jdbc/HikariPooledConnectionProvider.java, wrapper/src/main/java/software/amazon/jdbc/HikariPoolsHolder.java, wrapper/src/main/java/software/amazon/jdbc/LeastConnectionsHostSelector.java, wrapper/src/main/java/software/amazon/jdbc/PluginServiceImpl.java, wrapper/src/main/java/software/amazon/jdbc/RoundRobinHostSelector.java, wrapper/src/main/java/software/amazon/jdbc/hostlistprovider/monitoring/MonitoringRdsHostListProvider.java, wrapper/src/main/java/software/amazon/jdbc/plugin/AwsSecretsManagerCacheHolder.java, wrapper/src/main/java/software/amazon/jdbc/plugin/AwsSecretsManagerConnectionPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/efm2/MonitorServiceImpl.java, wrapper/src/main/java/software/amazon/jdbc/plugin/federatedauth/FederatedAuthCacheHolder.java, wrapper/src/main/java/software/amazon/jdbc/plugin/federatedauth/FederatedAuthPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/federatedauth/OktaAuthCacheHolder.java, wrapper/src/main/java/software/amazon/jdbc/plugin/federatedauth/OktaAuthPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/iam/IamAuthCacheHolder.java, wrapper/src/main/java/software/amazon/jdbc/plugin/iam/IamAuthConnectionPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterServiceImpl.java, wrapper/src/main/java/software/amazon/jdbc/plugin/strategy/fastestresponse/FastestResponseStrategyPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/strategy/fastestresponse/HostResponseTimeServiceImpl.java, wrapper/src/main/java/software/amazon/jdbc/util/Pair.java, wrapper/src/main/java/software/amazon/jdbc/util/RdsUtils.java, wrapper/src/main/java/software/amazon/jdbc/util/SlidingExpirationCache.java, wrapper/src/test/java/integration/container/TestDriverProvider.java, wrapper/src/test/java/integration/container/tests/AdvancedPerformanceTest.java, wrapper/src/test/java/integration/container/tests/PerformanceTest.java, wrapper/src/test/java/software/amazon/jdbc/HikariPooledConnectionProviderTest.java, wrapper/src/test/java/software/amazon/jdbc/plugin/AwsSecretsManagerConnectionPluginTest.java, wrapper/src/test/java/software/amazon/jdbc/plugin/federatedauth/FederatedAuthPluginTest.java, wrapper/src/test/java/software/amazon/jdbc/plugin/federatedauth/OktaAuthPluginTest.java, wrapper/src/test/java/software/amazon/jdbc/plugin/iam/IamAuthConnectionPluginTest.java
consolidate cache clean-up in a single place
@karenc-bq 
@aaron-congo 
=> consolidate cache clean-up in a single place

wrapper/src/test/java/integration/container/ConnectionStringHelper.java, wrapper/src/test/java/integration/container/tests/BasicConnectivityTests.java, wrapper/src/test/java/integration/container/tests/ReadWriteSplittingTests.java
test_pooledConnection_differentUsers was failing on multi-az mysql-latest with MariaDB. When trying to connect with the limited user the test was throwing the error "RSA public key is not available client side". Presumably this is because of some changes in the newest version of rds-mysql. The advice on this error message from stackoverflow was to set allowPublicKeyRetrieval to true.
=> test: fix test_pooledConnection_differentUsers

wrapper/src/main/java/software/amazon/jdbc/PluginServiceImpl.java, wrapper/src/main/java/software/amazon/jdbc/exceptions/AbstractPgExceptionHandler.java, wrapper/src/main/java/software/amazon/jdbc/exceptions/ExceptionHandler.java, wrapper/src/main/java/software/amazon/jdbc/exceptions/ExceptionManager.java, wrapper/src/main/java/software/amazon/jdbc/exceptions/GenericExceptionHandler.java, wrapper/src/main/java/software/amazon/jdbc/exceptions/MultiAzDbClusterPgExceptionHandler.java, wrapper/src/main/java/software/amazon/jdbc/exceptions/MySQLExceptionHandler.java, wrapper/src/main/java/software/amazon/jdbc/plugin/AuroraInitialConnectionStrategyPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/AwsSecretsManagerConnectionPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/iam/IamAuthConnectionPlugin.java, wrapper/src/main/java/software/amazon/jdbc/targetdriverdialect/GenericTargetDriverDialect.java, wrapper/src/main/java/software/amazon/jdbc/targetdriverdialect/MysqlConnectorJDriverHelper.java, wrapper/src/main/java/software/amazon/jdbc/targetdriverdialect/MysqlConnectorJTargetDriverDialect.java, wrapper/src/main/java/software/amazon/jdbc/targetdriverdialect/TargetDriverDialect.java, wrapper/src/test/java/software/amazon/jdbc/plugin/efm/ConcurrencyTests.java
remove CJException dependency from MariaDb (database) dialect
https://github.com/aws/aws-advanced-jdbc-wrapper/issues/1285
@karenc-bq 
@aaron-congo 
=> Remove mysql-connector-j library dependency for MariaDb

benchmarks/build.gradle.kts, wrapper/src/main/java/software/amazon/jdbc/PropertyDefinition.java, wrapper/src/main/java/software/amazon/jdbc/plugin/customendpoint/CustomEndpointMonitorImpl.java, wrapper/src/main/java/software/amazon/jdbc/plugin/customendpoint/CustomEndpointPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/efm/MonitorConnectionContext.java, wrapper/src/main/java/software/amazon/jdbc/plugin/efm/MonitorImpl.java, wrapper/src/main/java/software/amazon/jdbc/plugin/efm2/MonitorImpl.java, wrapper/src/main/java/software/amazon/jdbc/plugin/efm2/MonitorService.java, wrapper/src/main/java/software/amazon/jdbc/plugin/efm2/MonitorServiceImpl.java, wrapper/src/main/java/software/amazon/jdbc/plugin/failover2/FailoverConnectionPlugin.java, wrapper/src/test/resources/hibernate_files/hibernate-core.gradle
javadoc improvement
@karenc-bq
=> javadoc improvement

wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterMonitor.java, wrapper/src/main/java/software/amazon/jdbc/plugin/limitless/LimitlessRouterServiceImpl.java, wrapper/src/main/resources/aws_advanced_jdbc_wrapper_messages.properties
Fix connection leak issue due to Limitless Plugin not properly closing off monitoring connections
- Now doing check and close on monitor conns when monitor close is called and in finally block of monitor run
- Added an outer try catch finally and moved some of the exception catching there
=> fix: LimitlessRouterMonitor to close connection properly

wrapper/src/main/java/software/amazon/jdbc/plugin/AuroraConnectionTrackerPlugin.java, wrapper/src/main/java/software/amazon/jdbc/plugin/OpenedConnectionTracker.java
Clean up tracked connections in a background thread
https://github.com/aws/aws-advanced-jdbc-wrapper/issues/1390
@karenc-bq
=> clean up connections in a separate thread

wrapper/src/test/java/integration/util/AuroraTestUtility.java
The original storage type io1 only supports two availability zones. When creating 3-instance multi-az rds clusters we need 3 availability zones.
=> fix: change the storage type for multi-az clusters

wrapper/src/main/java/software/amazon/jdbc/util/telemetry/OpenTelemetryFactory.java
Fixed OpenTelemetry instrument name max length
OT Instrument name max length was not updated to new value from spec when in changed in 2023.
https://opentelemetry.io/docs/specs/otel/metrics/api/#instrument-name-syntax
=> Fixed OpenTelemetry instrument name max length

README.md, docs/using-the-jdbc-driver/using-plugins/UsingTheFailoverPlugin.md
Clarifies support for blue/green deployments by specifying minimum versions.
Clarifies support for blue/green deployments by specifying minimum versions.
=> docs: clarify support for blue/green deployments

wrapper/src/main/java/software/amazon/jdbc/ConnectionPluginFactory.java, wrapper/src/main/java/software/amazon/jdbc/plugin/customendpoint/CustomEndpointPlugin.java, wrapper/src/main/java/software/amazon/jdbc/util/connection/ConnectionService.java, wrapper/src/main/java/software/amazon/jdbc/util/monitoring/MonitorService.java, wrapper/src/main/java/software/amazon/jdbc/util/storage/CacheItem.java
=> Fix javadoc warnings/errors

wrapper/src/main/java/software/amazon/jdbc/util/telemetry/DefaultTelemetryFactory.java
Use `telemetryMetricsBackend` instead of `telemetryTracesBackend` in the RuntimeException when an invalid metrics backend is configured.
Fix incorrect variable in telemetry metrics backend error message
Fixed a bug in `DefaultTelemetryFactory` where the error message for invalid metrics backend configuration was displaying the wrong variable value. 
**Issue:** When an invalid `telemetryMetricsBackend` value was provided, the RuntimeException incorrectly showed the `telemetryTracesBackend` value in the error message, making it confusing for users to identify which configuration was actually invalid.
**Fix:** Changed line 64 to use `telemetryMetricsBackend` instead of `telemetryTracesBackend` in the exception message.
**Before:**
```java
throw new RuntimeException(
telemetryTracesBackend + …
```
=> fix: correct variable in telemetry metrics backend error message

aws-advanced-jdbc-wrapper-bundle/build.gradle.kts, build.gradle.kts, examples/AWSDriverExample/build.gradle.kts, examples/DBCPExample/build.gradle.kts, examples/SpringHibernateBalancedReaderOneDataSourceExample/build.gradle.kts, examples/SpringHibernateBalancedReaderTwoDataSourceExample/build.gradle.kts, examples/SpringHibernateExample/build.gradle.kts, examples/SpringTxFailoverExample/README.md, examples/SpringWildflyExample/spring/build.gradle.kts, wrapper/build.gradle.kts, wrapper/src/test/build.gradle.kts
- upgrade AWS SDK to 2.32.29
- remove pom dependencies
@karenc-bq
=> chore: remove pom dependencies

docs/using-the-jdbc-driver/using-plugins/UsingTheCustomEndpointPlugin.md, wrapper/src/main/java/software/amazon/jdbc/plugin/customendpoint/CustomEndpointMonitorImpl.java
handle unauthorized exceptions while getting custom endpoint details
https://github.com/aws/aws-advanced-jdbc-wrapper/issues/1513
- handle RdsException associated with user lack of permissions; use some delay before trying again
- use reduced refresh rate (5min) when IAM user has no permissions to get custom endpoint details
- handle throttle exception and reduce refresh rate
@karenc-bq
=> bug: handle unauthorized exceptions while getting custom endpoint details

README.md
docs: add supported versions for bg support in readme
docs: add supported versions for bg support in readme
=> docs: add supported versions for bg support in readme
